### ISSUE TITLE
to retest in the next build: grammar is sticky to last viewed section

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#105]
the grammar does not refresh in this situation: lookup for melior, click on adjective, scroll grammar to a different section, then close and go back to lookup and click on 1st declension, it will show the last viewed section of grammar, not the 1st declension. this is reproducible on firefox, not chrome.  will keep an eye on this one and retest on next build.

**Comment by monzug** [comment]
it might be related to issue #168

**Comment by monzug** [comment]
it does still happen in the latest build 2.0.2.3

**Comment by balmas** [comment]
will take this one to investigate

**Comment by balmas** [comment]
hmm. can't reproduce.

**Comment by monzug** [comment]
tested in build 2.0.3.4 in Firefox. grammar is sticky. 
e.g. lookup for  'mare'  and click on noun. it will take to the noun section of the grammar. close the grammar then click on 3rd declension, it will go again to the noun section of the grammar. close grammar, click on adjective, it will open the noun section of the grammar again. note that switching from noun (or 2nd declension) and case (dat, ablat or gen) works fine. also it can be sticky when scrolling, e.g. go to noun section, scroll down, then close grammar and go to 2nd declension, it will show the last viewed section of the grammar.
it looks like that it works fine when going to different sections of the grammar (from verbs to irregular or from noun to adverb --e.g.  'caro' ), but not in the same section, then it's sticky.

**Comment by balmas** [comment]
ok, thanks that helps. I am able to reproduce now. Will investigate.

**Comment by monzug** [comment]
all I can say is that I haven't seen it in some builds and I have seen in
others...

**Comment by balmas** [comment]
it seems it may be caused by a security restriction Firefox imposes on the iframe content which prevents it from navigating to anchor tags within the same document. I'm not sure if that fully explains it because I would expect it to behave the same regardless of whether you close the panel in between requests.  Experimenting now to see if there is an easy solution.

**Comment by monzug** [comment]
fascinating, right?

**Comment by balmas** [comment]
ok, think I found a solution for this in https://github.com/alpheios-project/res-client/issues/2 Will give you a build soon.

**Comment by balmas** [comment]
Ready for testing in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-5

**Comment by monzug** [comment]
tested in Firefox build 2.0.3-6
looks good. Thanks for fixing it
