### ISSUE TITLE
Question: Firefox misteriously uninstall on its own

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#106]
Hi guys,
need help on this one. it might be some setting that I am not aware of.  it did happen at least 3 times. on firefox  I found the webextension gone and I had to reinstall it, usually after few hours of not using it. any idea?
Thanks
version 2.0.2.2

**Comment by irina060981** [comment]
Hello, Monica!

The problem with disappearing a web-extension connected with that fact, that it is not signed by mozilla and considered to be malicious. And Mozilla trys to support a better security.

There are two ways (from my knowledge may be Bridget or Kirill knows better) for installing webextension:

1) simply using **about:debugging**
![image](https://user-images.githubusercontent.com/12377640/44459448-09171380-a64d-11e8-80f1-77c92670e49c.png)
It doesn't need and additional settings and a custom version of firefox.
But you could see that - it is temporary and clears between sessions in Firefox.

2) constant way - for this variant you need:
    a) special eddition of Firefox - I am using Firefox Developer Eddition - https://www.mozilla.org/ru/firefox/developer/

![image](https://user-images.githubusercontent.com/12377640/44459535-601ce880-a64d-11e8-8f67-47fcc6a3bde1.png)

b) you should set a config option 'xpinstall.signatures.required' to false in **about:config** there
   (Mouse Double Click)
![image](https://user-images.githubusercontent.com/12377640/44459654-c30e7f80-a64d-11e8-92cc-c3d8bb427e5c.png)

c) you should create a one archive zip file with *.xpi with all webextension files (I have done it with the help of 7zip)
![image](https://user-images.githubusercontent.com/12377640/44459716-f94bff00-a64d-11e8-8bc4-b54f29026247.png)

d) then you should simply drag it to firefox
![image](https://user-images.githubusercontent.com/12377640/44459754-197bbe00-a64e-11e8-8166-4a0cf1fe1978.png)

e) it will ask you
![image](https://user-images.githubusercontent.com/12377640/44459783-2f897e80-a64e-11e8-9cf4-33058623f251.png)

f) click Add and it appears in the browser
![image](https://user-images.githubusercontent.com/12377640/44459820-4a5bf300-a64e-11e8-9e2b-8d981c78fb0a.png)

And won't disappear between session

When you will need to update it - you should completly remove it as any other constant extension and istall a new version from the same built archive

Hope it will be helpfull for you :)

**Comment by monzug** [comment]
Irina, Thanks so much. I thought there was a timer issue. glad there is a workaround!

**Comment by irina060981** [comment]
Great :)

**Comment by balmas** [comment]
@irina060981 would you mind adding these instructions and explanation to the developer documentation in https://github.com/alpheios-project/documentation/tree/master/development ?

**Comment by irina060981** [comment]
Ready - https://github.com/alpheios-project/documentation/blob/master/development/install_webextension_firefox.md
