### ISSUE TITLE
on Firefox, extension is deactivated when navigating in grammar 

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#110]
Copied from https://github.com/alpheios-project/inflection-tables/issues/141

have grammar open on any section on Firefox, reload the page not the
extension, grammar panel is generated. scroll down to any other section,
the extension icon turns grey. if you move away from grammar, the
functionality is there.

tested in Chrome and this does not happen. reinstall the new build in
firefox and confirm that the extension goes grey when scrolling the grammar
(follow steps as per above description)

The cause is that Firefox resets the title and icon for the extension whenever the user navigates to a new page, even when that navigation event occurs inside a frame in the page. We update the webextension state, including the icon, whenever the user navigates to a new page in a tab the main browser window, but we don't want to do that when they navigate in one of the embedded frames. So we apparently need to add an extra test just to make sure the icon is updated when the user navigates within an iframe.

**Comment by balmas** [comment]
Ready for testing in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-5

**Comment by monzug** [comment]
testes on Firefox, latest build 2.0.4-5
the webextension does still toggle between on/off when going to any section of the grammar. it's so fast that you can barely notice it. I would say it's a go. Bridget?

**Comment by balmas** [comment]
yeah, there isn't much more I can do to improve on this while we still use iframes for resources like the grammar.  I entered https://github.com/alpheios-project/components/issues/204 to request that we consider other ways of serving this data in the future.
