### ISSUE TITLE
Pop-up is not draggable in one site

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#114]
tested in Firefox on build 2.0.3-5
Usually I move the pop-up so I can see inflection tables and morphology. when I drag the pop-up somewhere, it does disappear on this site
https://it.wikiversity.org/wiki/I_verbi_particolari_latini_(superiori)#Eo,_is,_ivi_/_ii,_ire_(Andare)

**Comment by monzug** [comment]
in an other case. if I drag the pop-up then it goes all the way behind the browser navigation and sticks there. the only option for me is to reload the page. this is in
http://www.poesialatina.it/_ns/Greek/testi/Homerus/Odyssea01.htm

**Comment by balmas** [comment]
something about the HTML or CSS of these pages is causing the interact.js library we use for dragging to calculate the clientY of the onMove event incorrectly (e.g. -869.5)

@kirlat maybe we should add safety here to make sure the coordinates produced by the onMove event aren't off screen?

**Comment by balmas** [comment]
(NB this doesn't seem to be specific to Firefox. It also happens in Chrome)

**Comment by monzug** [comment]
I did install the build only in Firefox when tested this issue. I can confirm that it's also in Chrome. Thanks Bridget!

**Comment by balmas** [comment]
I think that's a good compromise solution.

**Comment by monzug** [comment]
tested in few sites. now the pop-up moves only right to left and left to right in the sites mentioned above. In other sites, I can drag it anywhere on screen. Looks good to me.

**Comment by kirlat** [comment]
Great, I will prepare a PR then

**Comment by balmas** [comment]
this is in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-8
