### ISSUE TITLE
activation after new build 2.0.3-5 installed 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#115]
in Chrome:
after installing the latest build 2.0.3-5, the info panel is generated in most of the sites. Only in the following sites, after activating the webextension I need to reload to have the functionality
1) https://www.lexilogos.com/english/greek_ancient_dictionary.htm
2) http://www.atuttascuola.it/siti/zacco/seconda/verbi_composti_e_irregolari.htm
3) https://it.wikibooks.org/wiki/Greco_antico/Aggettivi_della_seconda_classe

in Firefox, same as above for the following sites:
1) http://dcc.dickinson.edu/allen-greenough/Chapters/Chapter-100.html
2) http://www.tradurreantico.it/latino/grammatica-latina/morfologia/verbo/verbo-eo-latino/
3) https://www.skuola.net/universita/appunti/lingua-e-letteratura-latina-schemi
4) https://www.quora.com/What-are-the-oldest-works-on-Greek-and-Latin-grammar-and-what-are-their-dates
5) https://it.wikiversity.org/wiki/I_verbi_particolari_latini_(superiori)#Eo,_is,_ivi_/_ii,_ire_(Andare)

in the following sites, the functionality is frozen and can't do anything. Unfortunately I do not have a reproducible scenario, but I have seen it today at least twice. I'll keep an eye on this.
https://www.studenti.it/verbi_anomali.html
https://www.quora.com/What-are-the-oldest-works-on-Greek-and-Latin-grammar-and-what-are-their-dates

**Comment by balmas** [comment]
This is odd. One possibility is if these pages are taking a long time to fully load, or if they have broken javascript themselves, the Alpheios functionality might not get fully loaded properly into them. Most of these pages do seem to have either javascript errors, or security violations for cross-domain requests, or warnings about slow loading resources.   I'm not sure there is much we can do about functioning properly in these situations.

**Comment by monzug** [comment]
I do also think that not properly deactivating the webextension can create
problem when installing the new build. see  #113

**Comment by balmas** [comment]
yes, that is entirely possible. I think it's okay for the beta release, needs further attention afterwards so let's leave this open.

**Comment by monzug** [comment]
reassign to myself to test again in new build post-release and in safari

**Comment by monzug** [comment]
tested in Chrome and FF build 2.1.017. all sites listed above generate the info panel on activation. 
I can confirm that lookup does not work in https://www.studenti.it/verbi_anomali.html

**Comment by balmas** [comment]
@monzug lookup is working for me at https://www.studenti.it/verbi_anomali.html in Chrome and Safari. What words aren't working for you?

**Comment by monzug** [comment]
Confirm that all sites work on Safari, including studenti.it.

**Comment by monzug** [comment]
reconfirm that lookup for caro in studenti.it does not work (Chrome)
