### ISSUE TITLE
safari: activate/deactivate context menu item doesn't change status of icon

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#124]
In Safari, when activating/deactivating the extension using the context menu item the Alpheios toolbar icon badge and text aren't updated.

**Comment by irina060981** [comment]
@balmas, @kirlat , there is a problem with this case. I wil describe it.
There are two workflows to change toolbar properties (image, badge, label):

1) Click on a toolbarIcon -> executes `SafariExtensionHandler.toolbarItemClicked` -> it has `SFSafariWindow` property -> I could execute `updateIcon with `SFSafariWindow` property and get access to toolbarItem
This workflow is successful - badge and label could be changed according to our needs

2) Click on a contextMenuItem -> executes `SafariExtensionHandler.contextMenuItemSelected` -> it has only `SFSafariPage` in properties - so I couldn't execute `updateIcon` and I don't have access to toolbarItem.
Apple documentation offers the way to handle with it - use `SafariExtensionHandler.validateToolbarItem`, it has `SFSafariWindow` property and `updateIcon` could be used.
But I didn't find the way to initiate it manually.

The documentation says the following ([source](https://developer.apple.com/documentation/safariservices/safari_app_extensions/safari_app_extension_info_property_list_keys/adjusting_settings_for_a_toolbar_item)):

*State changes can be triggered in either of these ways:
a) Safari can decide, based on the user's actions, that the button's state might need to be changed.
b) Your app extension can force a state change to happen explicitly.*

The b) - the first workflow, a) - the second workflow.
*When an event occurs that may require your toolbar’s state to change, Safari calls your app extension’s event handler. The event handler receives parameters that indicate the window the toolbar is displayed in and a completion handler for your app extension to call. Your event handler should determine whether to enable or disable the toolbar button and whether to display a badge, and then should return this information to Safari.*

It works this way - if you change state using context menu - for example, activate - the badge won't change, but if you after that click another tab and return to this, or minimize and then maximize and so on - it will init validation and update Icon.

I spent time (before your changes for badge - I was changing icons) but didn't find the solution.
May be we should ask apple team on some forum or any other way?

**Comment by balmas** [comment]
@irina060981 is there any way to call the `setToolbarItemsNeedUpdate()` method of the `SFSafariApplication` proxy? Do we have access to that object? It seems that's what triggers the validateToolbarItem handler

**Comment by irina060981** [comment]
Thank you, @balmas! It was very helpful!
Created PR - https://github.com/alpheios-project/webextension/pull/132

**Comment by irina060981** [comment]
Merged and closed
