### ISSUE TITLE
review memory management for safari

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#125]
> Hello, @balmas, @kirlat and @monzug!
> Only now I was able to rebuild safari extension with all new libs (because there were some strange problems with XCode - it seems to me that Apple tools are not so perfect as it is declared).
> 
> And I could see that it uses more RAM than in Chrome (I didn't compare with Firefox if to be honest)
> 
> It used in 300-600 Mb RAM, and some processes clearing in memory happens with greater delay than in Chrome.
> Here are some screenshots
> <img alt="screen shot 2018-10-03 at 19 33 16" width="1380" src="https://user-images.githubusercontent.com/12377640/46403106-f2340880-c744-11e8-8244-b91e600d45e3.png">
> 
> <img alt="screen shot 2018-10-03 at 19 34 00" width="1413" src="https://user-images.githubusercontent.com/12377640/46403114-f52ef900-c744-11e8-84e7-ad90f6364e4d.png">
> 
> <img alt="screen shot 2018-10-03 at 19 34 39" width="1353" src="https://user-images.githubusercontent.com/12377640/46403143-0d9f1380-c745-11e8-91ab-6af3c609858d.png">

**Comment by balmas** [comment]
@monzug please let @irina060981 know if you need help testing this. Thanks!

**Comment by monzug** [comment]
Could not detect any relevant difference in activity monitor. @irina060981  are you running specific processes? I just lookup for latin or greek words in safari, chrome and firefox but could not see much difference in memory. Thanks

**Comment by monzug** [comment]
check the memory tab in the activity monitor for few words, the memory usage was not more than 50 MB

**Comment by balmas** [comment]
ok. thanks!
