### ISSUE TITLE
optimize loading of resources for Safari

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#126]
as discussed in alpheios-project/safari-app-front#3, on Safari it seems the alpheios code gets injected in every page regardless of whether or not the user activates it for the page. We should probably delay some of the resource initialization code, such as loading of the inflection tables, until the user requests them.

**Comment by balmas** [comment]
I believe this can be closed with Build 2.1.0.5. Not sure it can be fully tested, other than to look at how memory is consumed in the browser. Handing to @monzug -- feel free to just remove the waiting_verification label  if you can't test it though.

**Comment by monzug** [comment]
related to issue #125  - haven't noticed any memory leak
