### ISSUE TITLE
safari: define, document and automate qa/production build process

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#127]
We need to define, document and ideally automate the process of building qa and producing builds of the Safari App Extension.

The Apple documentation on this is a bit difficult to comb through and they want you to use all of their tools (XCode to make the archives, XCode Server to setup continuous integration, etc.).

It looks like we can define some provisioning profiles for distributing archives to test machines, and it's not clear to me if we can use their TestFlight option to actually distribute test builds to the app store for download (it seems that this might only be for iOS, tvOS and watchOS but I'm not sure)

Some requirements to consider:
* it must be possible to identify which version of the library dependencies that are used to build the archive and to rebuild the archive exactly 
* it must be possible to distinctly identify the specific build version of the archive in the info panel of the extension (in the case of the ff/chrome extension this is pulled from the manifest file, which currently gets incremented manually when I create a QA or production build for testing)
* ideally we would not version the dmg files themselves in GitHub (but we can consider attaching them to GitHub releases ... see https://help.github.com/articles/creating-releases/)

Some additional notes:

I have gone ahead and creating a  production signing certificate, an AppID and a Distribution Provisioning Profile in the developer dashboard for the Alpheios MacOS App. I think we will need these for the production build and we will need to be sure to use the production certificate to sign that build.

It seems we could also create a Development Provisioning Profile to and register specific device ids that can install archives that were signed with our developer certificates. I'm not sure if that's totally necessary but it could be helpful.

**Comment by irina060981** [comment]
About testing - according to this article - there is no need now to have an outstanding XCode Server for testing or other tasks - Xcode has its own one - inbuilt.
https://medium.com/xcblog/hands-on-xcuitest-features-with-xcode-9-eb4d00be2781

Also there are some frameworks for testing in the article that can be used for unit testing, performance testing and UI testing.

Here it is a video about different features
https://developer.apple.com/videos/play/wwdc2017/409/

**Comment by balmas** [comment]
Thanks very much for this @irina060981. Your documentation was very helpful. 

I really struggled for hours with XCode to get it to let me sign the code. Since the Safari app extension is just one small piece of what we are doing,  I think I would like as much as possible getting too embedded with Apple specific tools here.  I might be willing to live with a manual build process for the extension right now as long as it's well documented and repeatable. 

Will spend a little more time on this tomorrow and provide more feedback, once I am recovered from today's fight with XCode and the MacOS :-)

**Comment by irina060981** [comment]
Yes, I agree with building and packing manually for now, I agree that we have more priority tasks for now :)
I hope you will be successful with all signing process.
I use keychain for working with certificates.

**Comment by balmas** [comment]
I will add some notes to the document you started on the problems I had with the keychain and how I resolved them.

**Comment by balmas** [comment]
build is documented in the BUILD.md file at the root of the webextension repo. See also #145
