### ISSUE TITLE
add help text to mac app splash screen

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#131]
We need to add some help text to the splash screen of the Alpheios App to tell users how to enable it.  See the following  example from another app:

![screenshot 2018-10-26 08 45 13](https://user-images.githubusercontent.com/644870/47567163-ccd98b00-d8fb-11e8-946e-a6ff68a1582f.png)

Alpheios 
Provices clickable access to dictionary entries, morphological analyses, inflection tables and grammars for Latin and Ancient Greek and limited support for Classical Arabic and Persian.

1. Open Safari application
2. Open Safari Preferences Window in Menubar [ show shortcut ]
3. Choose Extension Tab
4. Check "Alpheios" 

Then activate on a page with Latin, Ancient Greek, Arabic or Persian text by clicking on the Alpheios icon in the Safari toolbar [ add icon here if possible ]. Double-click on a word to retrieve morphology and short definitions.

**Comment by irina060981** [comment]
great, I have seen some tutorials how to work with this view controller and how to handle with some inputs (while tried to understand how to create an extension), it is time to use it :)

**Comment by irina060981** [comment]
Created - PR https://github.com/alpheios-project/webextension/pull/132
<img width="497" alt="screen shot 2018-10-29 at 22 50 30" src="https://user-images.githubusercontent.com/12377640/47651139-15c86280-dbce-11e8-8870-25c051a4d743.png">

**Comment by irina060981** [comment]
Merged and closed
