### ISSUE TITLE
safari: colors for the splash screen help text

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#134]
Can we use the Alpheios color (i.e. alpheios-link-color 3E8D9C) for the header on the splash screen?

**Comment by irina060981** [comment]
Yes, I could change it through properties - I will make changes after @kirlat will finish with merging his PR to avoid additional problems with it :)

**Comment by irina060981** [comment]
Fixed - https://github.com/alpheios-project/webextension/pull/144

**Comment by irina060981** [comment]
merged and closed
