### ISSUE TITLE
Double-click ignores some uppercase letter in bold

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#137]
in http://thelatinlibrary.com/plautus/mercator.shtml, the first letter of the row is uppercase and bold format such as Missus Requirit etc. when double-click on such words, it takes only the word without the first letter, so the morphological output fails (e.g. Amat is mat). is there anything that can be done?

**Comment by monzug** [comment]
got it. not sure how common it is. I have seen this issue only on this site
so far.

**Comment by monzug** [comment]
an other one from https://www.dizionario-latino.com/dizionario-latino-flessione.php - the endings are in one color and the lemma is in an other, so depending where I click on the verb, it takes only the initial part of the word or the ending. in both cases the lookup fails. e.g. amas lookup is either am or as

**Comment by balmas** [comment]
closing in favor alpheios-project/components#337
