### ISSUE TITLE
site with few problems

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#139]
on this site
http://www.tradurreantico.it/latino/grammatica-latina/morfologia/verbo/verbo-eo-latino/
we have few problems
1) double click does not work
2) the style of the info panel or morphology panel is so different from same page in Firefox
e.g. no navigation etc.
![screen shot 2018-10-30 at 3 10 26 pm](https://user-images.githubusercontent.com/41396793/47724085-39cf8680-dc56-11e8-9870-c79dfba2789e.png)

**Comment by balmas** [comment]
Assigning to @irina060981 to investigate. Style is probably related to #135 but the problem with the event not working is likely a new issue.

**Comment by irina060981** [comment]
Styles - are from the same problem.
About double-click - it is an interesting issue about setting *user-select:none* to body.
It fails with this bug:
<img width="832" alt="screen shot 2018-10-31 at 18 55 47" src="https://user-images.githubusercontent.com/12377640/47776658-a3c35b00-dd3e-11e8-886d-12d62b13a236.png">

And it fails for doc.caretRangeFromPoint return null if this style is applied.
When I removed it from the styles (manual in Web Inspector) - double-click starts to work.

I am not sure if we should redefine such styles - anyway - for now for Safari I haven't found any answers about such a problem (with style priority).
I am confused so far

**Comment by irina060981** [comment]
https://github.com/alpheios-project/webextension/issues/135

**Comment by balmas** [comment]
ready for testing in build 2.1.0.9

**Comment by monzug** [comment]
tested in 2.1.0.10 - style and double click has been fixed. Thanks
