### ISSUE TITLE
use of LexicalData object needs rework

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#14]
currently the content script aggregates the word data in a single LexicalData object which is defined in the inflection tables library. We need to rework this. Not all languages will *have* inflection data and so we should have a dependency on language definitions from that library in order to present results from other services.  

For the moment, in order to get Persian and Arabic results to display, I have created a branch of the inflection tables library in which getSuffixes just returns a LexicalData object instead of throwing an error for unsupported languages. https://github.com/alpheios-project/inflection-tables/commit/d643ac472fbf32c1a6a244511b7d4ac9f5b8d263

But this is not the right fix. Instead, we should break this dependency.

**Comment by kirlat** [comment]
Agree. I think we need to have some generic object that would represent language information about a homonym. Should we use a Homonym object and extend it dynamically with some additional properties (i.e. inflections property will hold inflections and so on)? Or shall we create a separate object? What do you think?

**Comment by balmas** [comment]
I'm not sure. I think extending the Homonym object sounds like a good way to start.
