### ISSUE TITLE
safari: app help remove or provide minimal page

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#143]
The Safari App as a Help menu item which just produces a message saying that Alpheios has no help.  We should either remove the menu item, or if that's not possible, the provide a minimal help page which essentially reproduces the instructions on the splash screen, maybe with the addition of the text from the info panel.

**Comment by irina060981** [comment]
Fixed - https://github.com/alpheios-project/webextension/pull/144

**Comment by irina060981** [comment]
Merged and closed
