### ISSUE TITLE
we should update the Alpheios icon in the dock 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#152]
right now, it looks like it's out of focus. we should have a new one for the dock when u mouse on.

**Comment by balmas** [comment]
@monzug I'm not sure I understand which icon you are talking about and what you mean by "mouse on".
Can you attach a screenshot with details? Thanks!

**Comment by monzug** [comment]
mouse over on the Alpheios icon in the dock. the icon is out of focus - see
screenshot

**Comment by balmas** [comment]
I don't have a screenshot but I think I see what you mean. It looks okay in the fixed dock but is fuzzy in the one that appears when you control tab through the open apps. I am currently looking at hiring a designer to help with some things and this may need to wait until then.

**Comment by balmas** [comment]
Safari Build 3.0.0.24 (in the Dropbox folder) has the new icons. @monzug let me know if it looks better to you.

**Comment by monzug** [comment]
I did not succeed with the installation (missing from the extension tab in
safari). however I could mouse over the Alpheios logo and it does still
look not quite right. see screenshot

**Comment by balmas** [comment]
hmm. I wonder if it actually got installed because it looks pretty good for me (the color is slightly lighter than previously -- this is because we are sticking to the new design palette)

**Comment by balmas** [comment]
![Screenshot 2019-04-02 08 10 25](https://user-images.githubusercontent.com/644870/55401508-ffc52200-551e-11e9-8fb0-06ab8360dab8.png)

I can't figure out how to get a screenshot of the command+tab dock open

**Comment by monzug** [comment]
it didn't get install for sure. shouldn't the icon still be the right one?
oh well, if it's good for u, then it's ok.
to take screenshot, do command shift 4

**Comment by balmas** [comment]
Let's just leave this open until you can verify it with a clean install.

**Comment by monzug** [comment]
I had install the other dmg as there was no date on the reading tools. I did download it but it does not open. is there anything different that I have to do?

**Comment by balmas** [comment]
Ah, I think this is my fault. I forgot the step of building the dmg .. when I test I just use the folder. Let me build you an image. Sorry!!

**Comment by monzug** [comment]
No problem at all. At least I know what's going on.

**Comment by balmas** [comment]
Image is there now!

**Comment by monzug** [comment]
YES!!!! I can see the new logo in lighter blue and the mouse over. I'll
take a screenshot in a sec (I have to switch to mac)

**Comment by monzug** [comment]
![Screen Shot 2019-04-02 at 2 51 55 PM](https://user-images.githubusercontent.com/41396793/55404063-6e25d680-5557-11e9-86ca-f198944539eb.png)
