### ISSUE TITLE
(Greek) is not hidden in lookup - Safari

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#153]
in safari we have greek in parenthesis next to the lookup word in morphology panel. This is inconsistent with Chrome and Firefox.
@balmas comment: It's actually there but hidden that in the other 
browsers. Another indication of Safari's different handling of styles - 
it isn't correctly applying the style instruction to hide it.
We had some debates early on about whether or not to include that, so it 
was hidden rather than taken out entirely. We could probably just take 
it out. 
![screen shot 2018-11-06 at 3 32 35 pm](https://user-images.githubusercontent.com/41396793/48071894-a6f59580-e1db-11e8-8c85-c71cd4433a28.png)

**Comment by irina060981** [comment]
There was a problem with verboseMode in all browsers - Chrome, Firefox, Safari.
I have fixed it 
**Chrome**
![image](https://user-images.githubusercontent.com/12377640/48697374-2cdbfc80-ec30-11e8-9139-c0279f12fe32.png)

**Safari**

**Comment by balmas** [comment]
Ready for testing in build 2.1.0.9

**Comment by monzug** [comment]
this is fixed in build 2.1.0.9 - Thanks
