### ISSUE TITLE
Inconsistency in the page context menu

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#154]
First, we should remove the Open Panel menu item from Chrome and Firefox context menu when tools are active and the panel is not open. the context menu should be only   -Deactivate  -Info.
When tools are not active, we should only have Activate (info does the same thing as Activate so it's redundant).
As per toolbar menu, we have Alpheios Reading tool (beta) that takes to the Alpheios.net site in Chrome, with tools active or not. in Firefox, we have -Activate -Info when tools are not active and -Deactivate -Open Panel -Info when tools are active. We should implement the same changes as per context menu.
The inconsistency between context menu and toolbar menu is Alpheios Reading tools that in Chrome toolbar menu links to the Alpheios site.

![screen shot 2018-11-06 at 3 18 44 pm](https://user-images.githubusercontent.com/41396793/48075124-c04e1000-e1e2-11e8-9c3b-4f2c1d8967bf.png)

**Comment by balmas** [comment]
oh... I thought you were talking about the right click context menu on the page itself, not the context menu for the icon. I don't actually know how much control we have over this menu.

(Although one of the long outstanding issues is that we should make use of the browser options menu for the extension -- see #78)

**Comment by monzug** [comment]
yes, that was the misunderstanding. it's toolbar menu vs context menu. I
entered this issue so we have both in one place

**Comment by balmas** [comment]
I don't think we have any control over the context menu on the toolbar icon but we can investigate this. I would like to separate it out into its own issue though since we don't currently have any code for this at all.

**Comment by balmas** [comment]
This item should now only cover the page context menu (i.e. a right quick or equivalent on the page rather than on the toolbar icon)

1. Remove the Open Panel menu item from the context menu when tools are active and the panel is not open. the context menu should be only -Deactivate -Info.
2. When tools are not active, we should only have Activate (info does the same thing as Activate so it's redundant).

**Comment by balmas** [comment]
@irina060981 can you take a look at this?

**Comment by balmas** [comment]
please test in build 2.1.0.12 all browsers

**Comment by monzug** [comment]
let me clarify the question about panel not generated on activate. so, if I do use the context menu to activate the tools after installing a new build or opening for first time the tab etc, I get the info panel. any subsequent activation does not generate the info panel. should it be?

**Comment by balmas** [comment]
it doesn't offer the Info menu option if the panel is open. It should if the panel is closed though. That is what I was seeing. Does it match with your experience @monzug ? Does it make sense for the user?

**Comment by monzug** [comment]
if I use activate/deactivate from the context menu, I do not get the info panel on activate (panel on activate is checked). the info panel option in the context menu works perfectly.

**Comment by balmas** [comment]
ah, that's interesting. Is that the case for all browsers or just safari?

**Comment by balmas** [comment]
Assigning to @kirlat -- to clarify, the problem @monzug is seeing is that the panel isn't opening upon activation, with Panel on Activate checked, if the context menu item is used to activate the tools, rather than the icon.  I think this might be limited to Safari but am waiting for confirmation.

**Comment by balmas** [comment]
(assigning to @kirlat instead of back to @irina060981 because it's in the same area of code as #176)

**Comment by monzug** [comment]
yes.

**Comment by monzug** [comment]
tested in Chrome and FF, build 2.0.1.14.
1) Panel on Activate is checked
info panel is generated when clicking on Activate from context menu. if info panel is already open , Deactivate is the only option in context menu. If info pane is not open, Deactivate, Info are the two options in context menu. 
If Tools are not active, Activate is the only option in context menu.
2) Panel on Activate is not checked
info panel is not generated on Activate from context menu or by clicking the icon. info panel is generated only by clicking info from context menu.
PROBLEM: when I check again Panel on activate option, the info panel is not generated on activation anymore (e.g. thelatinlibrary.com) in both FF and Chrome.
EXCEPTION: in Firefox, if Panel on activate is unchecked, the info panel is still generated in poesialatina.it.

**Comment by balmas** [comment]
this should be fixed in build 2.1.0.16

**Comment by monzug** [comment]
retested in Safari, Chrome and FF, build 2.1.0.16, the info panel is generated on activation after rechecked the Panel on activate option. YES, IT WORKS!
