### ISSUE TITLE
please hide dictionary title from arabic lookup

### ISSUE THREAD

**Issue by ghost** [alpheios-project/webextension#156]
this

"From An Advanced Learner's Arabic-English Dictionary (H. Anthony Salmoné, Beirut, Librairie du Liban, 1889)"

It is rare dictionary, I already know it, you may include it to "options/about" section or smth

**Comment by balmas** [comment]
I am not sure I understand this request can you provide a bit more explanation? We currently offer Lane as the default dictionary, with an option to include Salmone or not.

**Comment by MastQ** [comment]
where meanings of words appear in side-window there is dictionary title mentioned among, it appears many times and for me it is unnecessary info

**Comment by balmas** [comment]
Will be addressed vi alpheios-project/components#345
