### ISSUE TITLE
make the panel more responsive to content

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#16]
need to experiment with this a bit, but it would be nice if the panel size adjusted itself for certain content.
For example, with the inflection tables, it might be good for it to expand to show the full table. But maybe it should only do this on hover or some other user action?

**Comment by balmas** [comment]
as part of this, we might want also to adjust the opacity of the panel slightly so that it's clear that it's an overlay

**Comment by kirlat** [comment]
That is a good idea, I'll do that.

**Comment by balmas** [comment]
closing as mostly done. Will add new issues for specific requests.
