### ISSUE TITLE
Safari: double clicking instability after installation

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#164]
after installing a new build (in this case 2.1.0.7), the double-clicking does not work properly. this might be related to issue alpheios-project/components/issues/280  and  #160, I will update this one with a screenshot.
Activate the tool for page http://www.thelatinlibrary.com/lucretius/lucretius2.shtml
double click on the words of the first two rows, sometimes double click opens up the correct morphology popup for the word, sometimes it does not. e.g. double click on mare, it brings up the morphology for Options, double click on  turbantibus, brings up the Credits or in same other word. sometimes, double click on spectare, brings up Suave morphology popup.
I could not find any reproducible scenarios, but looks like it's related to first words of the text. see screenshots below.
also, Alpheios is deactivated after browsing to other pages, again not always

![screen shot 2018-11-16 at 11 26 01 am](https://user-images.githubusercontent.com/41396793/48616859-254cf700-e995-11e8-9c42-c1006f4a7477.png)

![screen shot 2018-11-16 at 11 25 21 am](https://user-images.githubusercontent.com/41396793/48616828-09495580-e995-11e8-87e9-6c07474f76b4.png)

**Comment by balmas** [comment]
I was experiencing something similar myself when using the latest components code with the embedded library yesterday.  @kirlat I was able to reproduce this pretty easily by introducing a breakpoint in the debugger, so I think it may have to do with timings of initial activation.  Can you take a look at your changes and see if you can see anything that would cause this?

**Comment by balmas** [comment]
@monzug is this still an issue in build 2.1.0.11?

**Comment by monzug** [comment]
to retest in incremental build
