### ISSUE TITLE
Safari: can't move the footnotes pop-up 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#168]
Safari, build 2.1.0.10
check footnotes pop-up and notice that the pop-up is way up the page so I cannot close the pop-up and cannot move it down, the only option is to close the inflection table.
see screenshot
![screen shot 2018-11-21 at 4 02 20 pm](https://user-images.githubusercontent.com/41396793/48849595-fbd20800-eda6-11e8-8a7c-25cd5c2d9df7.png)

**Comment by irina060981** [comment]
After some investigation - the probem was with `transform` property - that we define in style and inline - so there was a conflict (like previous width and display).
I have fixed it here - https://github.com/alpheios-project/components/pull/291

**Comment by irina060981** [comment]
merged and closed
