### ISSUE TITLE
need to reset background status after page refresh

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#17]
After refreshing a page, the content script is no longer loaded in the page but the background script still thinks it is, and the message sending fails

we need to watch page reload events and reinitialize

**Comment by kirlat** [comment]
Totally agree, will work on that after other bigger changes

**Comment by balmas** [comment]
working on this myself now. Will send a PR pretty soon.

**Comment by balmas** [comment]
think this is done for now. will revisit extension state more thoroughly soon though.

**Comment by balmas** [comment]
reopening and reassigning to @kirlat because the latest state changes may have broken this?

**Comment by balmas** [comment]
ok, retested - activation/deactivation state is still correctly being retained. Panel status is not. closing this and opening a new issue for panel status.
