### ISSUE TITLE
Safari: tools deactivated after browsing to a new tab

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#170]
Originally reported in issue #164 - Alpheios is deactivated after browsing to other pages.
tested again in 2.1.0.11 in http://thelatinlibrary.com/lucretius/lucretius2.shtml

**Comment by balmas** [comment]
I would guess that this was caused by, or at least is related to the change in 84296dceca5330333893b6c2c955ec6a75d80659 for #162 

We ideally want alpheios to stay active once activated in the browser tab, so that if you navigate to new pages you don't have to keep reactivating it. Is there a conflict between this functionality and resetting state on page reload? can we distinguish between those scenarios?

**Comment by balmas** [comment]
See also #171

**Comment by kirlat** [comment]
While working on #170 I tried an approach that can allow us to disable icon and menu item on sites where extension will be disabled (i.e. with frames). This is how it works.

Once content script is loaded into a page with frames, it creates a state with `DISABLED` status and sends that to the Safari app extension. Once the app extension receives this message, it knows that a content script cannot be run within this specific tab. Then the extension disables a button and a menu item that activates an Alpheios content script so the script can never become active.

It worked well in my tests, but I don't have an extensive suite of test cases for that. So maybe I include it to the build and we'll give it a try? What do you think?

**Comment by kirlat** [comment]
Made some changes to eliminate this behavior. Will issue a PR for this.

**Comment by balmas** [comment]
please test in build 2.1.0.12. Changes affect Safari as well as FF and Chrome so please test in both.

**Comment by monzug** [comment]
Tested in Safari in build 2.1.012 - happy to say that the issue reported above is not longer reproducible.
need to test in FF and Chrome

**Comment by monzug** [comment]
tested again in build 2.1.0.13 in safari. chrome and FF. tools stay active while browsing through the tabs on same browser.
