### ISSUE TITLE
panel re-appearing on page reload in Chrome after tools are deactivated

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#171]
Maybe caused by some of the changes we made to activation state handling for Safari, if you use the latest webextension and components code in the Chrome webextension, the panel reappears on page reload after you have deactivated the tools. To reproduce:

1. navigate to a page (e.g. www.thelatinlibrary.com/apuleius/apuleius4.shtml)
2. activate Alpheios by clicking on the icon
3. deactivate Alpheios by clicking the icon again
4. reload the page in the browser

The Alpheios panel reappears.

**Comment by kirlat** [comment]
I think I found a solution for this one. I will check other related issues and will try to fix them as well. They seem to be related, so the fixes should better go together.

**Comment by balmas** [comment]
please test in build 2.1.0.12.  Changes affect Safari as well as FF and Chrome so please test both.

**Comment by monzug** [comment]
tested in all 3 browser in 2.1.0.13. no panel is generated on page reload with tools not active
