### ISSUE TITLE
the alpheios embedded response isn't working right for any browser now

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#176]
I'm not sure if this wasn't working perfectly in 2.0.3.x either but it's very off now.

The way this was designed to work is the following:

1. user clicks icon or context menu item to Activate
2. background process executes a script in the current page page that sends Alpheios_Embedded_Check Event on document.body
3. Alpheios embedlib has a listener on Alpheios_Embedded_Check and issues in response an Alpheios_EmbeddedResponse Event
4. Content script has a listener for Alpheios_Embedded_Response in which it saves the current activation status of the script and then sets the UIController state to disabled
5. Background process receives a message and updates the icon title to show that it is disabled

This isn't working very well in the 2.1.0.x branch right now in FF/Chrome, even as designed, because with refactoring the call which sent the updated state to he background (https://github.com/alpheios-project/webextension/blob/release-2.1.0.x/src/content/content.js#L90) was commented out. So now the background only updates the icon if some other state request manages to trigger it

And it's not working at all in Safari right now because nobody is ever sending the Alpheios_Embedded_Check event.

**Comment by balmas** [comment]
@kirlat I have a start on this in https://github.com/alpheios-project/webextension/tree/issue-176 but I haven't tested it or finished the UI for Safari. I'm afraid other tasks are bogging me down this week though and I would like to get a new build to Monica soon, so if you don't mind I'm going to hand it off to you.

For now, I would like the Safari UI to just be the same as FF/Chrome -- i.e. when the extension is disabled due to the presence of the embedded library in the page:
-[] the icon should remain in the off state
-[] the icon tooltip should say "(Alpheios Extension Disabled For Page)"
-[] the context menu should just have a single, non-functional menu item which says "(Disabled)"

And for all browsers, the extension should be able to send the Alpheios_Embedded_Check and handle the Alpheios_Embedded_Response whenever it is activated, whether this activation occurs by:
- [] clicking the icon
- [] using the context menu Activate item
- [] as the result of a page reload which tries to "restore" an activated state

This means the Alpheios tools should enter this disabled state in all of the following scenarios:

Scenario 1:
1. User is on a page which does NOT have Alpheios Embedded
2. User activates Alpheios
3. User navigates to a page which DOES have Alpheios Embedded
4. Alpheios extension automatically enters the "disabled" state
5. User navigates away to a page which does NOT have Alpheios Embedded
6. Alpheios extension automatical returns to the previous "active" state

Scenario 2:
1. User has not yet activated Alpheios for the page
2. User navigates to a page which has Alpheios Embedded
3. User clicks the Alpheios icon OR user selects the "Activate Alpheios" context menu item
4. Alpheios extension should enter disabled state
5. User navigates to a page which does NOT have Alpheios embedded
6. Alpheios remains in "inactive" state until the user tries again to activate it.

**Comment by kirlat** [comment]
Thanks for a detailed description. I will try to fix this ASAP.

**Comment by kirlat** [comment]
I've made fixes for the "disabled" menu item text in Safari and for all browsers to retain panel state between inter-page navigations.

**Comment by balmas** [comment]
A commemt on the "(Disabled)" context menu item -- I had changed this to "(Alpheios Disabled)" in Safari because in Safari we don't have the Alpheios menu item in the context menu.  i.e. in FF/Safari we have:

Alpheios -> 
   (Diabled)

But in Safari just:

(Disabled)

with no indication that it has to do with Alpheios.  I don't know if we can have a sub menu in Safari, nor do I care too much about it, as long as the items we add to the context menu are clearly for Alpheios

**Comment by balmas** [comment]
In build 2.1.0.15 Dropbox for Safari and https://github.com/alpheios-project/webextension/tree/qa-2.1.0.15/dist for FF and Chrome expect that

- (Alpheios Disabled) remains as context menu item for Safari when on embedded library page, because we don't have the Alpheios submenu 
- Safari should now respect state of panel/tab between pages

See more in #174

**Comment by monzug** [comment]
build 2.1.0.16 - confirmed that in Safari on page reload the below comment reported previously is still reproducible: 
 - Scenario 1b: YES in Chrome and FF. in Safari on page reload of the test site with embedded library, the tools are activated (red icon is on).

**Comment by balmas** [comment]
See notes in https://github.com/alpheios-project/embed-lib/issues/27, I cannot reproduce the problem in Safari. @monzug please clear browser cache on Safari and try again ?

**Comment by kirlat** [comment]
@balmas, that might be a timing issue described in https://github.com/alpheios-project/embed-lib/issues/27#issuecomment-446552969. It might be failing in some tests and succeeding in others. And this is ... expected? I think embedded lib sending a message when activated and a UI message upon extension's deactivation might do the good.

**Comment by monzug** [comment]
to be retested with fix #27

**Comment by balmas** [comment]
Please retest in Build 2.1.0.17 (in Dropbox and https://github.com/alpheios-project/webextension/tree/qa-2.1.0.17/dist) using http://www-test.alpheios.net/alpheios-texts/Perseus.text.1999.02.0066/book1_poem1.html for the embedded library test page. Clear your browser cache first to be sure to get the updated code on the embedded page.

I haven't been able to reproduce this myself, but you should see a message if the page with the embedded library loads after the extension is already activated.

**Comment by monzug** [comment]
there is only a quick activation (Alpheios icon turns blue) when clicking on the icon just after opening the site for the first time in FF and Chrome. other than that, it looks good.
in Safari, I am not longer able to reproduce the activation in the embedded library test page. the red icon was on only once and got the message, see attachment. GOOD!!!!!

**Comment by monzug** [comment]
@balmas, see message above. I closed this issue, feel free to reopen it if there is anything u don't like in the message.
