### ISSUE TITLE
handle invalid page language code

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#18]
A possibly common scenario is the language for an html page being set to 'en' (or other default language of an html authoring tool) even if the content is another language. We could try to handle this by defaulting to the user's preferred alpheios language if the language identified in the page isn't one that we support

**Comment by kirlat** [comment]
We definitely need to handle situations like that, will work on the issue

**Comment by balmas** [comment]
related to #30

**Comment by balmas** [comment]
I believe this has been addressed now.
