### ISSUE TITLE
implement logout of AuthO

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#192]
The BGAuthenticator logout method currently removes the stored token but it doesn't actually log the user out of the AuthO service. In a situation where a user uses Alpheios on a shared machine, they might think they are logged out but they aren't really. Unfortunately it looks like we probably need to do this in an iFrame for the webextension because it isn't exposed by the AuthO api without a redirect url , and registering a redirect url isn't feasible for the webextension.  (see https://github.com/auth0/auth0.js/issues/618)

**Comment by balmas** [comment]
https://stackoverflow.com/questions/26080632/how-do-i-log-out-of-a-chrome-identity-oauth-provider

**Comment by balmas** [comment]
this is partially implemented now (for Chrome). It uses the change in alpheios-project/auth0-chrome#1 which fetches the Auth0 logout url. This works to log the user out of the Auth0 session, and it results in the logout url for the application being displayed in a popup window. I'm not sure if there is any way to avoid that behavior. The logout page is currently configured as a page on our server, so we could maybe tell it to close itself or something.

**Comment by balmas** [comment]
@kirlat please let me know if you can come up with any improvements to what I did here

**Comment by balmas** [comment]
I think this has been addressed now for Chrome and FF by using interactive=false on the logout call.  Giving to Monica to test.

**Comment by monzug** [comment]
tested in Chrome build 3.0.0.23
when I logout, the side and top navigation should go back to the initial state: either only the Alpheios icon + the lookup and option to expand or with the following icons open already: help, browse inflection table, grammar, option, user login. right now I do have all the icons that were active with previous user including the world user example. 
see screenshot
![top-nav-too-many-icons](https://user-images.githubusercontent.com/41396793/55814461-944df800-5abc-11e9-9933-09c4927c8476.JPG)

**Comment by balmas** [comment]
entered #221 for remaining issue.
