### ISSUE TITLE
make alpheios panel location configurable

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#2]
to display on right or left side of the screen should be user-configurable

**Comment by kirlat** [comment]
Great idea! Will implement that.

**Comment by balmas** [comment]
@kirlat I think this is done now, correct? If so, feel free to close.
(One thing I noticed though, which maybe should be fixed first, the left right arrows for expand or collapse don't make as much sense when the panel is on the right side. Either we should reverse what they do (e.g so that the right arrow collapses and the left expands, or use a different paradigm)

**Comment by balmas** [comment]
this is working now.
