### ISSUE TITLE
panel z-index needs to be higher (or user-manageable??)

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#21]
We should probably make the z-index of panel higher. The widely-used bootstrap theme I'm using for the alpheios.net web site uses 1030 as the z-index of its nav bar, causing the alpheios panel at z-index of 1000 to hide below it.

(found a little rant on this topic here of https://css-tricks.com/rational-z-index-values/. I looked at what hypothes.is does for their sidepanel and their z-index is a crazy high number )

There's no way we can make sure it's foolproof for all sites. I'm wondering if we want to consider a little ui widget that enables the user to bring it forward, similar in concept to resizing. maybe a question for a designer when we get one on board to help us.

**Comment by kirlat** [comment]
I've added a function that iterates over all HTML elements on the page and finds the one with the highest z-index. Then this index plus one is assigned as a z-index value of a panel. If max possible numeric value is used anywhere on a page (Number.POSITIVE_INFINITY), then it will not be increased by one and will be assigned to the panel without any modification. However, the fact that the panel was moved to the bottom of the page and will be the last element in an HTML source order will guarantee that the panel will be shown above any element on the page, even over the ones with the maximum possible z-index value.

Commit 507a0ec should fix the issue.
