### ISSUE TITLE
add status badge for chrome and ff too

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#210]
requested by @abrasax it seems that at least chrome supports badges on the toolbar icons and we'd like to use them to indicate status on chrome and ff too if we can.

**Comment by balmas** [comment]
@abrasax has also requested that instead of the open book emoticon we just use the word "on"

**Comment by irina060981** [comment]
As I could see Firefox has ability to add a badge
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setBadgeText

And Chrome could too - https://developer.chrome.com/extensions/browserAction#method-setBadgeText

**Comment by balmas** [comment]
yes, please go ahead and implement it. Thanks!

**Comment by irina060981** [comment]
Chrome
![image](https://user-images.githubusercontent.com/12377640/59900355-56197100-943b-11e9-95e5-742ebb2f25b7.png)

Firefox
![image](https://user-images.githubusercontent.com/12377640/59900373-64678d00-943b-11e9-8f8a-83427b41af19.png)

**Comment by irina060981** [comment]
Safari
<img width="872" alt="Screen Shot 2019-06-21 at 15 57 57" src="https://user-images.githubusercontent.com/12377640/59901166-bb6e6180-943d-11e9-8a94-57bae45e8f8c.png">

**Comment by irina060981** [comment]
I have also set muted color for badge in Firefox and Chrome (to be in brand color)
I didn't find the way to change the coor for Safari badge, but from my point of view it is not consistent to have red everywhere.

@balmas , what do you think - could we use muted and red in different extensions?
or should I do all in red?

**Comment by irina060981** [comment]
Changed to red and text badge to On
![image](https://user-images.githubusercontent.com/12377640/59994121-0e425600-9696-11e9-86cb-4ed934ed0301.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
I think we need some additional tests here, to make sure the initial state for a new tab has the badge text off

**Comment by balmas** [comment]
the code to set the badge text probably should be moved into the activateContent and deactivateContent methods, rather than in the browserActionListener

**Comment by irina060981** [comment]
I have made additional investigation - and it turns out to be a little more complex than simply move to activate/deactivate.
Because badge is not removed by default.

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
@monzug reports that the badge status is not being cleared when in the texts environment. Maybe the test for isEmbedLibActive() is failing?

**Comment by balmas** [comment]
Or maybe I haven't given an updated version of the webextension with this fix yet.  taking this myself to double check.

**Comment by balmas** [comment]
status badge should now be off in texts environment as long as the latest webextension is installed 
webextension qa-3.0.0.45/Safari3.0.0.45)/embed-lib 1.0.0.27

**Comment by monzug** [comment]
I have installed latest build in Chroma and FF. the on status badge gets contaminated when passing from web extension to text environment and back. see screenshots. 
![status-bar-on-2](https://user-images.githubusercontent.com/41396793/60980781-1f7c9b00-a303-11e9-8eb3-96137a9818f0.JPG)
![status-bar-on](https://user-images.githubusercontent.com/41396793/60980782-20153180-a303-11e9-9dea-5c1a0715197e.JPG)

**Comment by monzug** [comment]
![status-bar-on-3](https://user-images.githubusercontent.com/41396793/60982941-168dc880-a307-11e9-91bd-ec718d47bb13.JPG)

**Comment by balmas** [comment]
hmm, okay, so it's when switching between tabs that it's broken?

**Comment by monzug** [comment]
yes.

**Comment by balmas** [comment]
ok thanks, will fix.

**Comment by balmas** [comment]
fixed in in qa-3.0.0.46

**Comment by monzug** [comment]
tested in chrome and ff. fixed. thanks
