### ISSUE TITLE
The user could not log out from the extension

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/webextension#232]
@balmas , here it is an issue
The user is not really log out from the extention.
The steps to reproduce:
   - Activate the extension
   - Log in with any user
   - log out
    - Reload the page
The result you are again logged in. (Chrome extension and Firefox extension)

**Comment by balmas** [comment]
yep, I can reproduce this too. Will investigate.

**Comment by balmas** [comment]
qa-3.0.0.57/components 1.2.27 (still not in Safari)

**Comment by monzug** [comment]
@balmas, I think we had a discussion about this and my understanding was that we wanted to keep the user logged in on reload.

**Comment by balmas** [comment]
@monzug yes, but only if they hadn't explicitly logged out.  If you actually logout, it should not keep you logged in.

**Comment by monzug** [comment]
ok, my misunderstanding!!!!

**Comment by monzug** [comment]
tested in chrome and FF, when logged out you don't log in back after a reload.  I had the following experience in Chrome: only once the authentication window stayed open in the front but I could see that I was logged in.
see screenshot
![login-still on](https://user-images.githubusercontent.com/41396793/64033115-c7e7f800-cb19-11e9-8ede-b686bcc79e02.JPG)

**Comment by balmas** [comment]
hmm. I wonder if it that happens if you submit the login request from the extension twice? i.e. clicking it quickly twice?

**Comment by monzug** [comment]
it was my first attempt to login to test this issue. I don't think I
clicked twice to login

**Comment by balmas** [comment]
hmm. Not sure what to do about this. Can you reproduce the behavior?

**Comment by monzug** [comment]
Nope, I cannot reproduce.
