### ISSUE TITLE
Safari login form doesn't get updated after login

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#236]
the MacOS app login form does not get updated after successful login.

The username and password box remain present and filled in, and the message on the form says "You are logged out" even though the App Extension shows the correct user information on the tab and indicates that the user is logged in.

**Comment by balmas** [comment]
I think the username and password boxes should go away when the user is logged in, replaced with their nickname.

**Comment by kirlat** [comment]
> the message on the form says "You are logged out" even though the App Extension shows the correct user information on the tab and indicates that the user is logged in.

This is some of the quirks of the Safari app, I think. Once we send a login message to the Safari app extension, it gets focus automatically (this is part of the messaging functionality and is generally a nice thing) but as a result of this a containing app window (the one with the form) loses focus and goes to the background. As a result text changes that are made there will not be visible unless the app goes to the foreground. If to click anywhere on the form window, the text will be updated, but no sooner than that.

I'm not sure how to fix it, but I will investigate.

**Comment by kirlat** [comment]
> I think the username and password boxes should go away when the user is logged in, replaced with their nickname.

Maybe we should also hide Log in or Log out buttons depending on the authentication state? What do you think?

**Comment by balmas** [comment]
> > I think the username and password boxes should go away when the user is logged in, replaced with their nickname.
> 
> Maybe we should also hide Log in or Log out buttons depending on the authentication state? What do you think?

agree

**Comment by balmas** [comment]
> > the message on the form says "You are logged out" even though the App Extension shows the correct user information on the tab and indicates that the user is logged in.
> 
> This is some of the quirks of the Safari app, I think. Once we send a login message to the Safari app extension, it gets focus automatically (this is part of the messaging functionality and is generally a nice thing) but as a result of this a containing app window (the one with the form) loses focus and goes to the background. As a result text changes that are made there will not be visible unless the app goes to the foreground. If to click anywhere on the form window, the text will be updated, but no sooner than that.
> 
> I'm not sure how to fix it, but I will investigate.

that is very annoying.  I don't have any good ideas.

**Comment by monzug** [comment]
![Screen Shot 2019-09-11 at 2 03 52 PM](https://user-images.githubusercontent.com/41396793/64696197-198b6d80-d49e-11e9-80cb-ecde1c7d0d7f.png)

**Comment by monzug** [comment]
can we also add information on the required field for id/psw? I did enter an invalid one and did not get any feedback

**Comment by kirlat** [comment]
Working on improving this part right now...

**Comment by monzug** [comment]
Thanks

**Comment by kirlat** [comment]
This shall be working as desired with the latest changes introduced in the UI. I've seen occasional quirks in behavior here and there such as unreasonable long delay in UI updates or a focus halo for the element hidden. I don't understand their true reason. They happen not often and on an irregular basis. I will keep an eye on it and will fix whatever I can.

**Comment by balmas** [comment]
Safari build QA-3.0.0.70 (in Dropbox)

**Comment by monzug** [comment]
thanks for adding te check on id/psw. see the message truncated

![Screen Shot 2019-09-20 at 3 29 50 PM](https://user-images.githubusercontent.com/41396793/65330770-a9769900-dbbb-11e9-8b1b-b99b593e6d14.png)

**Comment by balmas** [comment]
that's in the Auth0 supplied form. I'm not sure we can do too much about it. I'll move it to a new issue.
