### ISSUE TITLE
Add tip about creating an account to Safari app login page

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#237]
Can we add some instructional text to the login form on the Safari MacOS application screen:

"To create your Alpheios account, please go to https://texts.alpheios.net/login and click the SignUp tab. Note that you must create an Alpheios user account. Log In via Google does not work for the Safari Alpheios Browser Extension."

**Comment by kirlat** [comment]
After discussion with @balmas we agreed that for better UX we can just add a "Sign up" button to the containing app's UI. This button will open a sign up page of Auth0 directly.
