### ISSUE TITLE
safari: don't send logout message before login occurs

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#238]
Right now, it looks like the MacOS app sends a logout message to the app extension before the user even tries to login. When you first launch the browser extension, it shows the Log Out notification message.

Is it possible to prevent this? And only send the Log Out notification when the user actually logs out?

**Comment by monzug** [comment]
same screenshot as per #236 
![Screen Shot 2019-09-11 at 2 03 52 PM](https://user-images.githubusercontent.com/41396793/64696346-7850e700-d49e-11e9-94cb-8bbb1ad02562.png)

**Comment by kirlat** [comment]
When a page with a content script is loaded for the first time, or reloaded, an app extensions is sending a state message to it. This message includes an authentication status, among other things. For the "Logged out" status we were mistakenly calling a logout method of an auth module that was causing the message mentioned above to appear. We should be doing nothing instead. This is the fix I did.

**Comment by balmas** [comment]
Safari build QA-3.0.0.70 (in Dropbox)

**Comment by monzug** [comment]
first we have: please enter your credentials to log in
if wrong id/psw: wrong email or password  or if  id/psw is missing:
Missing required parameter: username/password
when logged in it says: you are logged in as xxxx with the Log out button
