### ISSUE TITLE
Safari: Auth0 SignUp form truncates tooltip for password input

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#242]
see the message truncated

![Screen Shot 2019-09-20 at 3 29 50 PM](https://user-images.githubusercontent.com/41396793/65330770-a9769900-dbbb-11e9-8b1b-b99b593e6d14.png)

_Originally posted by @monzug in https://github.com/alpheios-project/webextension/issues/236#issuecomment-533554821_

**Comment by balmas** [comment]
this is in the Auth0 signup form. Will have to investigate if we can control this with the settings for the universal login.

**Comment by balmas** [comment]
I'm afraid this one is beyond my css hacking skills.

this popup appears in a div with the class auth0-lock-password-strength

Per the Auth0 css, on everything except small screens (min-width 481px) it gets positioned as a popup with the following additional css properties:

```
position: absolute;
background; #f14242e;
box-shadow: 0 0 20px 0 rgba(0,0,0,5);
width: 100%;
border-radius: 3px
z-index: 1000;
```

the problem is that on the signup form without the tabs and the google login, there isn't enough room in the parent element, which is relatively positioned, to display this popup which is 260x219px.  So it gets truncated.

On small devices, a popup isn't used, and it just gets positioned below the password box. 

As the Auth0 setup is designed to use a single, universal login form for all applications, it would take some serious contortions to implement some style overrides for just this scenario.  So, to fix we have to decide whether we want to optimize for this case, not using the popup anywhere, and always just displaying it below like on mobile, or do make the signup screen in this case a little white space heavy, introducing a margin or minimum size for the containing box so that there is room for the popup to appear.

@kirlat those are the only things I've been able to come up with. Passing to you to see if you have any better suggestions.

**Comment by kirlat** [comment]
Found a way to fix this by updating an overflow rule of a parent element located far away in a hierarchy.

**Comment by monzug** [comment]
looks good! see in safari 

![Screen Shot 2019-09-25 at 2 17 10 PM](https://user-images.githubusercontent.com/41396793/65600021-83783c80-df9f-11e9-944f-13b4b9145f9a.png)

**Comment by monzug** [comment]
tested also in chrome and FF
