### ISSUE TITLE
check accessToken expiration before issuing api requests

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#244]
I would like to increase the expiration on the access tokens to the maximum (30 days) to help ease the pain of the Safari authentication process. 

Before I do that though, we should probably test that the current expiration, of 2 hours, works properly.

@monzug right now, the user should be logged out after 2 hours. Can you verify that behavior in all 3 browsers?

**Comment by monzug** [comment]
Firefox: user test-login-1, access at 8.33am
Chrome: user coco, access at 8.39 am

**Comment by monzug** [comment]
Safari: user monicaz, access at 8.41am

**Comment by monzug** [comment]
Chrome: user Coco still logged in after more than 2 hours
FF: user test-login-1 still logged in after 2 hours
Safari: same as above
I logged in in teh 3 browser, lookup few words and then leave the browser open with Alpheios on and still logged in. after more than 2 hours I checked the status by performing a double-click. in all the browser I was still logged in and the words saved in user word list. @balmas, any other test I should perform for this one?

**Comment by balmas** [comment]
hmm. that's interesting. There are 2 possibilities:
1) I am misunderstanding which timeout is used for these tokens. There are 2 possible, one which is set for 24 hours and another which is set for 2. I thought our workflow would produce the one that times out in 2 hours but it could be the other.

2) the token is timed out but we are still allowing it to be used.  

3) the token is timed is timed out, and it looks like the save is succeeding, but it it isn't really

@monzug could you test the 3rd possibility for me, by looking up a word or two now after the two hours has passed, and then logout, when you login again, are the words you just added still in the list? 

If that's the case, then I will take this item back and see if one of the other two possibilities are what is happening. Thanks!

**Comment by monzug** [comment]
in FF, they are saved in word list after logged out and logged in again.

**Comment by monzug** [comment]
same in Chrome and Safari.

**Comment by balmas** [comment]
ok, taking this back for further investigation on my part. Thank you!

**Comment by balmas** [comment]
ah, yes it seems that the 24 hour expiration is what is applied.

@monzug can you leave this overnight and retest?

**Comment by monzug** [comment]
will do tonite! I just saw your comment, sorry.

**Comment by monzug** [comment]
FF: after almost 25 hours I am still logged as user test-login-1.

**Comment by balmas** [comment]
and still able to save words to the list?

**Comment by monzug** [comment]
yes. will also test chrome and safari over the weekend. it's difficult to
leave it there for 24 hours...

**Comment by balmas** [comment]
understood. Here's what I would expect to happen:

based upon the code, here are the various scenarios that I think would happen

Scenario (1) - session times out while alpheios is deactivated 
user loads page in browser
user activates alpheios
session check fails so user is not logged in

Scenario (2) - session times out while alpheios is active but not in use
user loads page in browser
session check fails so user is not logged in

Scenario (3) - session times out while alpheios is in use
user loads page in browser, session is activate, so saving words works and all is well
session times out, alpheios only checks the session on page load, so it thinks it is still logged in
saving words to the wordlists stops working, but user gets no notification (errors only appear in the developer's console)
next time they load the page, they will see they are logged out

I think the behavior in Scenario 3, assuming it happens as I expect, is not ideal. But I don't know how much to worry about it.

**Comment by balmas** [comment]
(the simplest solution in the short term would probably be to allow expired tokens on the words and settings apis)

**Comment by monzug** [comment]
so, after more than 24 hours, I was still logged in. however in Safari, the
ON icon was missing from he alpheios icon. I could perform double click and
added words to word list but word list did not have the context reference
for these new added words. Let me explain, context icon was there but when
clicking on it there was no reference text (empty). when back to word list,
the icon was not longer associated with these new added words (no more
contexts icon).
same in chrome (id:test). note that in Chrome the ON icon is there.
wordlist behavior is same as in Safari.

**Comment by balmas** [comment]
this is really odd. Ok, I'm going to take this back and try to setup an environment that is easier to test and debug. Thank you!

**Comment by monzug** [comment]
let me know if I can test anything else with this one.

**Comment by balmas** [comment]
thanks! I think we will have code for you soon to test :-)

**Comment by balmas** [comment]
per discussion with @kirlat and @irina060981 today, we should store the expirate date of the access token along with the access token in the auth data module, and check it before every call to the user apis (wordlist and settings). If it's expired, we can notify the user that their session is expired and bring them to the user tab.

@kirlat when you implement this, can you also implement a back-door feature (via the query param) that can be used to expire the access token immediately, so that monica can test without needing to wait for the 24 hours to elapse or me having to setup a completely alternate test auth0 application environment?

**Comment by kirlat** [comment]
I've added a support for an expiration date into the webextension, into the `webext-i244-token-expiration` branch. 

A `sessionDuration` URL parameter that specifies session duration in seconds (e.g. `sessionDuration=20`) can be used to decrease an expiration period for testing. There is one limitation in using the parameter though: expired session will not survive a page reload. This is because auth data is stored in the background and `sessionDuration` parameter does not update that data. So once the page is reloaded, the session will be valid again as long as an auth token in the background script is valid. 

Updating the background will require a new transaction, or a modification of an existing one, and that would be too much of a change in order to do testing only. But we can do that change if necessary.

I am working on adding support for an expiration date check into the embed lib and Safari (not sure if and what changes be required for the latter).

**Comment by balmas** [comment]
@kirlat I think this looks great. I was initially surprised by the use of setTimeout , as I was thinking we would make this check only whenever we did something that required a session but believe your approach is better. The only concern I have is whether setting a timeout with a long duration has any negative performance implications. I haven't seen it used in this way before myself

I do think we should probably set the timeout for the test id to something smaller than 30 days. I think it should actually be much less, probably just an hour.

**Comment by kirlat** [comment]
Thanks for testing it!
I believe timeout approach is simple because it allows to update the state once, at the exact time of timeout expiration. It also allow to eliminate the need for multiple checks in different places which can be more troublesome and error-prone. AFAIK timeout does not have any performance implications because it does not do much work: https://stackoverflow.com/questions/30351627/effect-on-performance-of-large-settimeout-time

I will update a test timeout period to be an hour.

**Comment by balmas** [comment]
ok, thanks. Then please go ahead and issue a PR to master. Thanks!

**Comment by kirlat** [comment]
All changes has been merged into master.

**Comment by balmas** [comment]
Safari/FF/Chrome Webext qa-3.0.1.75/components-1.3.0 (Safari build in Dropbox)
texts-text embed-lib 3.1.1.42/components-1.3.0

@monzug to test the timeout, activate alpheios, and then reload the page with the additional sessionDuration query parameter set to the number of seconds after which you want the session to be timed out.

e.g. https://thelatinlibrary.com/caesar/gall1.shtml?sessionDuration=30

after that number of seconds elapses, the next time you do anything that produces an Alpheios UI element (e.g. a lookup) you should see 
1- a notification that the session has timed out, 
2 - you are no longer logged in
3 - the wordlist is cleared

**Comment by monzug** [comment]
Fantastic! will try now.

**Comment by monzug** [comment]
tested in Chrome.
all works as per description. question: after timeout, if I remove the parameter from the URL, and reload page I am still logged in. is it ok?

see screenshot of the message in morphology pop-up
![time-out](https://user-images.githubusercontent.com/41396793/66132018-66a4c000-e5c2-11e9-8313-5627140eaaca.JPG)

**Comment by monzug** [comment]
and time out message in FF
![FF-time-out](https://user-images.githubusercontent.com/41396793/66132705-78d32e00-e5c3-11e9-8dac-2d14a2191b10.JPG)

**Comment by balmas** [comment]
> all works as per description. question: after timeout, if I remove the parameter from the URL, and reload page I am still logged in. is it ok?

Yes, this is expected. It is not how it will work when the session really times out. the sessionDuration query parameter does not affect the actual stored access token, it was just a way to simulate a timeout to make testing easier.

To fully validate this you would have to wait the 24 hours again, but we wanted to make it easier on you...

**Comment by monzug** [comment]
perfect. only safari left to test.

**Comment by kirlat** [comment]
@monzug, I think Safari might need a few tweaks to make it work. I will test it today and make any updates, if necessarily. This release was targeting primarily webpextension/embed-lib/Nemo UI on Chrome and FF.

**Comment by monzug** [comment]
it works also in Safari (after time out, wordlist is empty and user is not logged in). However I have an issue with authentication as it does always show "Authentication failed" message. 
see screenshot
![Screen Shot 2019-10-03 at 4 30 35 PM](https://user-images.githubusercontent.com/41396793/66136325-8e644a00-e5fb-11e9-9ba0-fc44dd51d4c5.png)

**Comment by monzug** [comment]
no problem. note that authentication was working fine in previous build.

**Comment by kirlat** [comment]
I've merged changes that should fix the Safari problem into the master branch now.

**Comment by kirlat** [comment]
Expiration of a user session in Safari via a `sessionDuration` URL parameter will not cause user to log in or log out in the containing app. It will also restore user as logged in after page reload. This is a limitation of the current implementation (similar to webextension).

**Comment by balmas** [comment]
qa-3.0.1.76 (Safari build in dropbox)

**Comment by monzug** [comment]
Now I am getting the correct message also in Safari. see screenshot below the questions
few issues/questions here:

1) I got "your session has expired" message  for any subsequent look-up after logged out. is there any setting for the number of times this message should be generated? if yes, how many look-ups?

2) in Safari, when I log in, my wordlist saved with user Coco is empty. in the other browsers, the word list is correctly loaded when I log in.

3) Is it ok that I am still logged in also after a fresh install with clear cache?

![Screen Shot 2019-10-04 at 2 41 25 PM](https://user-images.githubusercontent.com/41396793/66209394-8cf85780-e6b7-11e9-8892-80f33222c8ff.png)

**Comment by balmas** [comment]
>I got "your user session has expired" message for any subsequent look-up after logged out. is there any setting for the number of times this message should be generated? if yes, how many look-ups?

@monzug does it return if you close it?

**Comment by balmas** [comment]
>in Safari, when I log in, my wordlist saved with user Coco is empty. in the other browsers, the word list is correctly loaded when I log in.

@monzug just clarifying - you mean if you login after a timeout your wordlist is empty and not reloaded? Does it load on the initial login?

**Comment by balmas** [comment]
>Is it ok that I am still logged in also after a fresh install with clear cache?

This, I believe, is expected.

**Comment by kirlat** [comment]
>     3. Is it ok that I am still logged in also after a fresh install with clear cache?

The login status in stored in Core Data. So no matter what we do in a browser, it will be restored after app/browser/safari app extension is relaunched.

**Comment by monzug** [comment]
1) I did several lookup and I was still getting the message. If I go back to the "regular"environment I don't get the message because I am still logged in.
2) login as user Coco, my wordlist is loaded. reload page with the timer,  user is logged out and word list is empty. go back to "regular" environment, user Coco is logged in but wordlist is empty.
3) OK.

**Comment by balmas** [comment]
>I did several lookup and I was still getting the message. If I go back to the "regular"environment I don't get the message because I am still logged in.

I tested this, and if you close the message (by clicking on the icon) it goes away. I think it's okay that it shows up until you close it or login. It's different than the login notification message because since the user was previously logged in, we know that they have an account and a wordlist.  Do you agree?

**Comment by balmas** [comment]
>login as user Coco, my wordlist is loaded. reload page with the timer, user is logged out and word list is empty. go back to "regular" environment, user Coco is logged in but wordlist is empty.

@kirlat, can you look into this? it seems incorrect.

**Comment by kirlat** [comment]
> @kirlat, can you look into this? it seems incorrect.

Will investigate this. What is the "regular" environment? Is that the containing app's UI (please see below)?
![image](https://user-images.githubusercontent.com/18631055/66212930-d81e6480-e6cf-11e9-8eb7-acc94a650bb6.png)

**Comment by monzug** [comment]
the one that does not have the ?sessionDuration=30 in the link

**Comment by kirlat** [comment]
I just merged a fix for a wordlist into master

**Comment by balmas** [comment]
fix is in qa-3.0.1.77 (Safari build in dropbox)

**Comment by kirlat** [comment]
The Safari part probably needs to be retested since we've switched to using Auth0 SPA SDK library.

**Comment by monzug** [comment]
Safari: I retested it over the weekend for 3 times by waiting for 24 hrs when still logged in. below the findings:
1) the Alpheios icon has still the ON badge
2) user is still logged in
3) no messages on panels 
4) wordlist icon is enabled but only the words from last session are listed
5) activate/deactivate Alpheios: I get the Congratulations! you are logged in successfully
6) reload the page, I am still logged in but wordlist is empty and the Congratulations message is displayed on panel.
7) logged out / logged in again, reload the page, the correct wordlist for the user is displayed, but I am still getting the Congratulations message while in Firefox I don't
see screenshots of user account panel after 24 hrs (no messages) and of the user wordlist

![Screen Shot 2019-10-14 at 1 17 00 PM](https://user-images.githubusercontent.com/41396793/66748833-70fb6f80-ee88-11e9-86be-ff3a94e5c76e.png)

![Screen Shot 2019-10-14 at 1 17 23 PM](https://user-images.githubusercontent.com/41396793/66748841-7953aa80-ee88-11e9-9ed4-7d152884f0f5.png)

**Comment by balmas** [comment]
@kirlat I wonder if this is because of the difference in session handling? See my comments on the PR.

**Comment by monzug** [comment]
note that when I used the ?sessionDuration=30 setting, all works well.

**Comment by kirlat** [comment]
A fix has been merged into master. Due to limited time frame I was not testing it over prolonged periods of time, but let's hope there will be nothing like macOS power policies or something like that that will prevent it from working properly.

Will run a test on my machine for a day to see how will it behave.

**Comment by balmas** [comment]
QA-3.0.1.80 is in Dropbox

**Comment by monzug** [comment]
tested in build Safari App Extension 3.0.1.81. after 24hrs, user was still logged in. see screenshots of wordlist icon still active and no messages in user account page
1) page after more than 24 hrs
![Screen Shot 2019-10-16 at 4 02 09 PM](https://user-images.githubusercontent.com/41396793/66927114-8b238200-f02f-11e9-8476-6e3fdfe0bbfc.png)
2) user account page
![Screen Shot 2019-10-16 at 4 02 26 PM](https://user-images.githubusercontent.com/41396793/66927270-cde55a00-f02f-11e9-998d-c6b48da0ef3e.png)

**Comment by kirlat** [comment]
> important question: I just realized that I used the same account Coco on Chrome to test something else. would that matter in counting the 24 hours timeout or timeout is only related to the app where user is logged in?

Based on my past experience any subsequent login from any other app on any other client will restart the session and make it valid for the next 24 hours (or whatever time is configured in Auth0 settings). However, this probably does not matter for the Safari app extension as long as the extension does not send any additional requests to the auth0 server to receive an updated session information (which it should not).

I will try to run some tests to see if I can reproduce this or not. What was the exact test scenario? Did you close Safari and/or the containing app before leaving it off? Did you turn the computer off or did you put it to sleep?

An additional question: in your test, what will happen if you'll refresh the page? Will the user still be logged in? What will happen if you'll close the page and then reopen it activating an Alpheios extension after that?

**Comment by kirlat** [comment]
I think I've found a scenario where, if a UI controller is deactivated and Safari is reloaded, an authentication information within the Auth module won't be update. Maybe that was the case discovered by @monzug. Will work on a fix.

**Comment by monzug** [comment]
Great! Thanks for looking into it.

**Comment by balmas** [comment]
I tested this myself and what I saw was that the interface thought I was still logged in (i.e. showed my user details and the Log out button) but requests to the apis were failing.

I tested overnight, so the laptop was in suspend during it.

I tested first without reloading the page and then again after reloading, behavior was the same.

I am guessing that what is happening here might be related to the timeout taking effect while the laptop was in suspense, so that the javascript timer didn't run. That would explain at least why I got the errors after the timeout and before reloading.  But it doesn't explain why it was the same after reloading the oage, which should have called updateAuthData in the Auth Module and seen that the expiration interval was reached.

**Comment by kirlat** [comment]
I was testing it on my macBook and I've seen timeout been working, even after the machine went to suspend and was waken up. Before the macBook went to sleep, I had the Safari with the user tab open. When computer was waken up, I've seen that the user became logged out and there was a message about session being expired.

I will continue to investigate further.

**Comment by balmas** [comment]
ok. @monzug said she also got the expected results with the dev build using the 1 minute timeout.

I suspect there must be some weird combination of circumstances that allows this to occur, but am leaning towards resolving in an incremental at this point.

**Comment by kirlat** [comment]
I have a feeling it has to do with the way Safari manages the state of the Safari app extension (i.e. the Swift part of it). To be more precise, with the way Safari terminates it.

I've seen in logs that multiple instances of Safari app extension are created and terminated during the regular extension's lifecycle. They are represented by the SafariExtensionHandler class instances. Usually there is more than one SafariExtensionHandler created per tab. Maybe there is one instance created per request. I've seen instances created and terminated almost instantly, probably when they're done with what they were spawned for. I have not seen a description of any logic behind this anywhere, though.

We keep TabScript objects (that represent tabs that are running the content script; it should in theory be any tab or even iframe document in the browser except those that are filtered out by `isValidTarget()`). We use tab script objects to communicate with content scripts. It's basically a list of scripts known to the extension.

TabScript objects are stored in the BackgroundScript instance. It is a class variable of SafariExtensionHandler. In theory (how I understand it) it should exist no matter what. In practice, though, it seems that it needs probably at least one instance of SafariExtensionHandler to run or it will be destroyed. In logs I see that it gets destroyed quite often, after a period of browser's inactivity.

After it gets destroyed, the list of tab scripts is gone too. It means we might lose communication with the content script(s) and they might not receive all messages about the state change (i.e. log in, log out, session expired). That's why state of some pages may not get updated, and the countdown timer won't start, or the logged in or logged out state won't be reflected correctly. This may happen with greater chance for tabs which were not used for logging in.

It feels like the tab is stuck, reflecting an outdated state. Refreshing it, sometimes twice, usually fixes the problem. This is because when script is loaded on page refresh, it sends a `contentReady` message to Safari app extension making it to recreate a TabScript object. In a response to that, an app extension sends a state message containing a latest authentication status. That would make a tab to update itself and start a countdown timer, if necessary.

I will do more testing in an attempt to catch that exact moment where it fails. I just wanted to describe in details (for myself included) what the underlying mechanics might be. It might also matter if the tab that's having problems is the one through which the login was made. Other details about the exact sequence of actions can be of high importance too.

**Comment by monzug** [comment]
retested in Safari App Extension 3.0.1.82
Alpheios Components 1.4.1

after more than 24 hrs, I was still logged in, double click & wordlist worked normally, no logged out messages generated. on refresh, the wordlist icon was greyed out.

**Comment by balmas** [comment]
this changes can be tested in the Safari dev build of 3.0.2.84 (in Dropbox) . This build is set to use the dev environment with the 1 minute timeout.

It will require regressions on the FF and Chrome browsers too. That's in the tag qa-3.0.2.84 (https://github.com/alpheios-project/webextension/tree/qa-3.0.2.84/dist).

**Comment by monzug** [comment]
safari build 3.0.2.84 . after 1 minute, user got logged out. Session expired message is displayed in morphology panel. In user account, click on log in. However it does not log the user back in and the wordlist is empty, so the only sign that user is logged in is the congratulations message. if I keep clicking on log in, the authentication pop-up shows up briefly and then disappears. if I open a new tab with an other site (e.g. scaife) and activate Alpheios, I am logged in automatically as the user logged out in the first tab. however after the timeout, I am not longer able to log in again.
see screenshots
![Screen Shot 2019-10-24 at 6 33 06 PM](https://user-images.githubusercontent.com/41396793/67506115-ca378000-f68c-11e9-8540-5fbf5998c4ae.png)

![Screen Shot 2019-10-24 at 6 17 00 PM](https://user-images.githubusercontent.com/41396793/67505174-0ff34900-f68b-11e9-8db6-071f94bd2d4b.png)

**Comment by balmas** [comment]
@kirlat can you reproduce what Monica is seeing?

**Comment by kirlat** [comment]
Thanks for testing this!

> However it does not log the user back in and the wordlist is empty, so the only sign that user is logged in is the congratulations message.

I have not seen this in my testing, but I was testing a slightly different version. I will check with the latest release as maybe this is a side effect of the merge.

**Comment by kirlat** [comment]
> if I keep clicking on log in, the authentication pop-up shows up briefly and then disappears.

This is normal as if Auth0 thinks it has enough data to identify the user (it probably checks if there is an unexpired session cookie) will log the user in automatically. To get the login prompt you have to clear the Auth0 data in the browser and, maybe, restart it.

**Comment by balmas** [comment]
>However it does not log the user back in and the wordlist is empty, so the only sign that user is logged in is the congratulations message.

I am seeing this as well.

**Comment by kirlat** [comment]
> @kirlat can you reproduce what Monica is seeing?

I can see that too. That's very strange. I'll check if it's something with the merged code.
A page reload fixes the issue for me.

**Comment by balmas** [comment]
>A page reload fixes the issue for me.

yes me too

**Comment by balmas** [comment]
fix is in Safar build QA3.0.2.85-dev. 

it worked for me, except I had to move off and back on the user tab to get the Login button to display after the timeout. @monzug curious to know if you see the same.

**Comment by monzug** [comment]
I am about to install it.

**Comment by monzug** [comment]
![Screen Shot 2019-10-25 at 6 54 50 PM](https://user-images.githubusercontent.com/41396793/67589596-0df7bb80-f759-11e9-8ff2-37334df3c480.png)
![Screen Shot 2019-10-25 at 6 53 55 PM](https://user-images.githubusercontent.com/41396793/67589597-0df7bb80-f759-11e9-8ebe-78b19eb05b3d.png)
![Screen Shot 2019-10-25 at 6 42 45 PM](https://user-images.githubusercontent.com/41396793/67589600-0df7bb80-f759-11e9-9ddc-afd6c4c378fd.png)
![Screen Shot 2019-10-25 at 6 39 46 PM](https://user-images.githubusercontent.com/41396793/67589603-0df7bb80-f759-11e9-8302-2ded3adeccee.png)

**Comment by kirlat** [comment]
> as soon as I installed the new build, I got the above message. either time out kicked in by the time I navigated to the info panel or message is sticky.

This is because the previous session has been expired while you was not using the extension. The expiration datetime is stored internally, and once session expires, it will be marked so even if the extension is not in use or even if the browser is not active (I'm simplifying a little but this is how it should look to the user).

**Comment by monzug** [comment]
got it! Thanks

**Comment by kirlat** [comment]
> when I logged out intentionally (no time out), the authentication kicked in and I could enter the user credentials. when I time out, by clicking on Log in I am automatically logged in with last user credentials.

I don't know how but this is decided by Auth0 internally whether to ask for user credentials or authorize him/her silently. I think if the user is logged out explicitly, the session is considered terminated and Auth0 will always ask for user credentials (I'm not 100% sure of that but that's how it seems to behave). This allows user to log in again with a different account.

When the timeout is expired, and browser still has a session cookie valid (validity period is probably 24 hrs), it will authorize user silently (which is very convenient for the user, I think, but not so secure, or course). We probably has this discrepancy because in a test config we have a session duration (60 secs.) not matching the cookie (or whatever Auth0 uses) validity (which is probably 24 hrs.). In production version they probably will match (but may not as well).

@balmas, does such behavior create any problems for us? If so I can look deeper into it to see if we can change anything there.

**Comment by kirlat** [comment]
> also, when I logged out, there are no message in pop-ups/panels after I logged in again (e.g. you are logged in or session has timed out)
> when I timed out, messages are displayed in pop-up/panel. Note that the user is the same in both scenarios, so why this difference?

We have some fuzzy "do not show again" logic in place and maybe this is a result of that. I will look closer at the code. @balmas, what would be our desired behavior?

**Comment by balmas** [comment]
> > when I logged out intentionally (no time out), the authentication kicked in and I could enter the user credentials. when I time out, by clicking on Log in I am automatically logged in with last user credentials.
> 
> I don't know how but this is decided by Auth0 internally whether to ask for user credentials or authorize him/her silently. I think if the user is logged out explicitly, the session is considered terminated and Auth0 will always ask for user credentials (I'm not 100% sure of that but that's how it seems to behave). This allows user to log in again with a different account.
> 
> When the timeout is expired, and browser still has a session cookie valid (validity period is probably 24 hrs), it will authorize user silently (which is very convenient for the user, I think, but not so secure, or course). We probably has this discrepancy because in a test config we have a session duration (60 secs.) not matching the cookie (or whatever Auth0 uses) validity (which is probably 24 hrs.). In production version they probably will match (but may not as well).
> 
> @balmas, does such behavior create any problems for us? If so I can look deeper into it to see if we can change anything there.

Ah I think this might be an artifact of the test environment. Kirils's explanation makes sense. The login timeout in the dev environment is set to 1 hr (I think) while the api timeout is set to 1 minute. The api timeout is what we base the app timeout on. I think in normal production mode the api timeout will not be less then the login. @monzug I think I will change think I need to adjust the dev environment so that you get a 5 minute login timeout and a 10 min api timeout so that you can test something that more closely mirrors what users will see. I need to give you a new build for that though.

**Comment by balmas** [comment]
> > also, when I logged out, there are no message in pop-ups/panels after I logged in again (e.g. you are logged in or session has timed out)
> > when I timed out, messages are displayed in pop-up/panel. Note that the user is the same in both scenarios, so why this difference?
> 
> We have some fuzzy "do not show again" logic in place and maybe this is a result of that. I will look closer at the code. @balmas, what would be our desired behavior?

I think logout should reset any memory of whether we have shown the user these messages.

**Comment by balmas** [comment]
QA 3.0.2.86-dev safari build has a 1 minute timeout on the login and a 2 minute timeout on the access token. The expiration notice should popup after 2 minutes and it should require you to login again.  This should more closely mirror what the user will see in production.  @monzug let me know if it works

As for the issue with the notification messages not appearing after logout I could not reproduce that and cannot see any reason for it to occur in the code.

**Comment by monzug** [comment]
all good, including messages generated on timeout or logged out.
However, on install (or on alpheios activation), the session timed out message is displayed,  also after reloading the page. shouldn't messages be cleared after reload/restart the app? 
see screenshot
![Screen Shot 2019-10-28 at 3 58 22 PM](https://user-images.githubusercontent.com/41396793/67690186-bf3a6380-f99c-11e9-87af-1d162d5a9b5c.png)

**Comment by balmas** [comment]
this is by design. The login/session might have timed out while the application was active but the user was not, so we want to alert the user the first time the see the application after the timeout occurs. It's not perfect but I think it's better to show it than not.

**Comment by balmas** [comment]
ok, ready for regression testing of authentication in qa-3.0.3.87/components 1.4.5

**Comment by balmas** [comment]
please retest and do regressions with qa-3.0.3.90/components 1.4.7

**Comment by monzug** [comment]
tested the 24 hours timeout in Safari App Extension 3.0.3.90
Alpheios Components 1.4.7 and in the dev build 
No issues to report
