### ISSUE TITLE
Safari: after sign up successful message, no where to go

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#247]
tested in build Safari 3.0.0.70. after successfully sign up to Alpheios, I get the message but not indication where to go next. If I close the tab from the browser, I end up back in the previous situation with the option to log in to Alpheios. Shouldn't I automatically log in when signing up as a new user?
see screenshots

![Screen Shot 2019-09-26 at 3 20 21 PM](https://user-images.githubusercontent.com/41396793/65691657-85aacb80-e071-11e9-830e-8c2a8817839d.png)

![Screen Shot 2019-09-26 at 2 26 36 PM](https://user-images.githubusercontent.com/41396793/65691723-a3783080-e071-11e9-8cc8-b5e172216e22.png)

**Comment by balmas** [comment]
Ideally yes, but it's not possible in this implementation. We will have to list it in the FAQ and cover it in the tutorial. That's the best we can do for now.

**Comment by monzug** [comment]
we should add to FAQ or to tutorial as it's not really friendly

**Comment by balmas** [comment]
agree. Very little about the Safari authentication process is friendly...

**Comment by monzug** [comment]
We all know very well....

**Comment by balmas** [comment]
this one is obsolete now with the newer workflow.
