### ISSUE TITLE
Morphology pop-up is sticky to last word after activate/deactivate Alpheios while still logged in

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#248]
tested in Safari 3.0.1.72 and developer build. to repro:
1) log in and double click on some latin words from https://www.thelatinlibrary.com/martial/mart12.shtml.
2) close Alpheios, while still logged in. 
3) Reactivate Alpheios and double click on any latin word from above text. The morphology pop-up is the one of the last word lookup before closing Alpheios.
4) any subsequent double-click does show the same pop-up

**Comment by balmas** [comment]
@kirlat Monica says this is new in the latest build.

**Comment by monzug** [comment]
I think it's new but not 100% sure

**Comment by kirlat** [comment]
I can reproduce the problem, will work on fixing it

**Comment by kirlat** [comment]
This is a truly weird issue. We have a `createSelectionFromPoint()` function that creates a range for a selected word. On Safari it uses `doc.caretRangeFromPoint()` to create start and end ranges. Usually it works without any problem, but if to disable an Alpheios UI controller and enable it again after that (no matter logged in or not), this function returns a null object. As a result, selection for a double clicked word cannot be made and the old word is shown.

If to refresh a page, an issue is be fixed.

I will investigate it further.

**Comment by kirlat** [comment]
I think I've found a solution.

When we disable an Alpheios, we assign to the page body a class that prevents word selection. This is to prevent user from doing any word selection while an Alpheios is deactivated. However, we were not always removing this class after Alpheios is reactivated. This prevented `caretRangeFromPoint()` from working properly. 

A simple fix with couple of lines of code should fix that.

**Comment by kirlat** [comment]
@monzug I think this is a great catch! This code was there for like almost forever and we were not noticing; yet you've found a scenario where it showed.

**Comment by kirlat** [comment]
The fixes has been merged into `components#master`. It will require rebuilding a webextnesion in order for them be available in Safari.

**Comment by balmas** [comment]
qa 3.0.1.73/components 1.2.48 (Safari build in dropbox)

**Comment by monzug** [comment]
fixed. Thanks!
@balmas, question: in the user word list, when I limited by this session, I found the list of words from first login and second login. is it ok?

**Comment by balmas** [comment]
@monzug I think that's okay for now, but probably we ought to fix it in a future release. Will convert to a new issue.
