### ISSUE TITLE
Safari: after new sign up, the user account panel doesn't get updated

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#252]
tested in About Alpheios
Safari App Extension 3.0.1.78
Alpheios Components 1.3.0

Sign up a new user, then go to User panel. the user account panel doesn't get updated until I click again on the Log in button. Note that if I login as an existing user, the User panel does get updated immediately, including the congratulations message at the bottom.

![Screen Shot 2019-10-10 at 4 18 05 PM](https://user-images.githubusercontent.com/41396793/66578610-b7488a00-eb7b-11e9-9c0f-69805357c469.png)

![Screen Shot 2019-10-10 at 4 18 19 PM](https://user-images.githubusercontent.com/41396793/66578632-bf082e80-eb7b-11e9-8749-180f56ba1f95.png)

**Comment by kirlat** [comment]
This is a timeout issue. The default timeout of a login/create account popup is 60 seconds. If to enter user information not fast enough, the show login popup function will fail with an error. The following steps such as receiving user information will not be fulfilled and user info will not be shown.

The user account on the Auth0 side, however, will be created. The next time user presses Log In, correct user info will be retrieved and shown.

To prevent this, I set the timeout to be 5 minutes. Luckily for us, Auth0 SPA SDK provides such option. Should be plenty of time to enter new user credentials.

**Comment by balmas** [comment]
back to @monzug to retest.

**Comment by monzug** [comment]
uhm, as soon as I signed up successfully, I got logged out immediately after.
![Screen Shot 2019-10-14 at 1 51 23 PM](https://user-images.githubusercontent.com/41396793/66749288-c421f200-ee89-11e9-920e-48adf8dbe241.png)

**Comment by monzug** [comment]
Yes, it's working now. Thanks!!!!

**Comment by balmas** [comment]
actually, taking this back because I misunderstood - I thought a server-side change had been made, so we need to retest after a new build.

**Comment by monzug** [comment]
but it's working. any ideas?

**Comment by kirlat** [comment]
The timeout in the current build is 60 seconds. So if the signup takes less than that, it shall be working. But if to go slower, user info shall not be displayed.

**Comment by balmas** [comment]
maybe you tested more quickly the second time so the timeout didn't take affect?
I will have a new build later today. Waiting to see if we can squeeze a fix for #244 in before preparing it for you.

**Comment by balmas** [comment]
QA-3.0.0.81 is in Dropbox

**Comment by monzug** [comment]
Got the congratulations message immediately after signing up.
