### ISSUE TITLE
add button to open safari preferences to alpheios app

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#257]
per @kirlat the latest safari app extension api includes the ability to put a button on the app that opens the safari preferences button. We should do this.

**Comment by balmas** [comment]
3.0.1.81 (in Dropbox)

**Comment by monzug** [comment]
it's there. Not sure if it's clear enough that this is a button, can we add a click here or similar?

see screenshot
![Screen Shot 2019-10-15 at 3 27 01 PM](https://user-images.githubusercontent.com/41396793/66835801-75935700-ef60-11e9-81e9-7caceb18107d.png)

**Comment by balmas** [comment]
@kirlat let's change the button text to say Click to Open Safari Preferences and keep the 1 out of the button

**Comment by kirlat** [comment]
OK, will do that now

**Comment by kirlat** [comment]
@balmas: would something like below work?
![image](https://user-images.githubusercontent.com/18631055/66837833-b8f7c080-ef74-11e9-9351-38021ed4c3f9.png)

**Comment by balmas** [comment]
I think so. @monzug what do you think? Is it better?

**Comment by monzug** [comment]
absolutely

**Comment by balmas** [comment]
@kirlat please go ahead with the PR. Thanks!

**Comment by balmas** [comment]
3.0.1.82

**Comment by monzug** [comment]
changes are in. see screenshot
![Screen Shot 2019-10-16 at 4 07 02 PM](https://user-images.githubusercontent.com/41396793/66926947-38e26100-f02f-11e9-8a8a-9464efc45bda.png)
