### ISSUE TITLE
run script message on login form

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#259]
Also, when I hover over Don't remember your password, I see a Run script message, see below

![Screen Shot 2019-10-15 at 2 21 03 PM](https://user-images.githubusercontent.com/41396793/66832324-fd299780-ef59-11e9-80d0-61c2c58929eb.png)

_Originally posted by @monzug in https://github.com/alpheios-project/webextension/issues/245#issuecomment-542192165_

**Comment by balmas** [comment]
@kirlat can you take a look at the auth0 form and see if this can be addressed easily? thanks

**Comment by kirlat** [comment]
I can not reproduce this as of now. Maybe this is because Monica has passwords remembered and I don't. Will try to figure out.

**Comment by monzug** [comment]
yes, I do have many stored psw

**Comment by kirlat** [comment]
Enabled the password manager, but still do not see the run script message:
![image](https://user-images.githubusercontent.com/18631055/66836409-4dacef00-ef72-11e9-9a74-e549939a8782.png)
I'm wondering if this could be because of something else. @balmas, can you reproduce this in your environment?

**Comment by balmas** [comment]
I can reproduce it in Firefox only

**Comment by monzug** [comment]
I can see it in FF, in the left corner javascriptvoid (0)

**Comment by kirlat** [comment]
> I can reproduce it in Firefox only

> I can see it in FF, in the left corner javascriptvoid (0)

That's interesting because on Monica's initial screenshot there is Safari. As opposed to Safari, FF and Chrome are using auth0-chrome lib that employs Auth0 Lock widget, as opposed to Safari, where it's Auth0 SPA SDK.

**Comment by balmas** [comment]
In any event, I'm not sure we can do anything about this actually. Looking at the Universal Login form, I don't see the html for that button, I believe it's inserted by the Auth0 code. So let's just mark this one as won't fix.
