### ISSUE TITLE
Bugs with authentication

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/webextension#267]
@balmas and @kirlat 

Tested with Chrome
This error I have got after Login (I haven't enter credentials)
![image](https://user-images.githubusercontent.com/12377640/69060342-e992b480-0a62-11ea-8078-cfdf070873dc.png)

Then if I reload the page, it becomes authenticated
![image](https://user-images.githubusercontent.com/12377640/69060463-1e067080-0a63-11ea-87bf-142af9e72fd5.png)

Then I logout
then I login again - it gives me an ability to enter credentials
I enter google authentication
and it again fails the authentication
![image](https://user-images.githubusercontent.com/12377640/69060659-73428200-0a63-11ea-8320-12e9d1a472be.png)

I have made the following fix:
webextension / background / background-process.js
```
userProfileRequestHandler (request, sender) {
window.fetch(`https://${auth0Env.AUTH0_DOMAIN}/userinfo`, {
        headers: {
          Authorization: `Bearer ${this.authResult.access_token}`
        }
      })
        .then(resp => resp.json()).then((profile) => {
```
**if (!profile.userId) { profile.userId = profile.sub }**
```
this.messagingService.sendResponseToTab(UserProfileResponse.Success(request, profile), sender.tab.id)
            .catch(error => console.error(`Unable to send a response to a user profile request: ${error.message}`))
        })
```

This fix has solved the bug

**Comment by balmas** [comment]
@monzug can you reproduce this?

**Comment by monzug** [comment]
Can't have an empty user id. it does either prompt for an existing google is or to enter a new one. If I do not feel the required fields for new id, it does not create a new user. Irina, how did you get to have an empty field without failing authentication?

**Comment by irina060981** [comment]
I didn't register - I used my existed google account to login.
So I didn't enter any data manually.

**Comment by monzug** [comment]
I do login with my existing account to

**Comment by monzug** [comment]
![image](https://user-images.githubusercontent.com/41396793/69062930-9b8d9a80-09e9-11ea-9e55-05fa018c3e18.png)

**Comment by balmas** [comment]
interesting. I will investigate a bit, looking into Irina's account on Auth0 to see if there are any differences there.

**Comment by balmas** [comment]
@irina060981 can you verify which version of the webextension code you are looking at?

the code that is in master has the following:

```
  window.fetch(`https://${auth0Env.AUTH0_DOMAIN}/userinfo`, {
        headers: {
          Authorization: `Bearer ${this.authResult.access_token}`
        }
      })
        .then(resp => resp.json()).then((profile) => {
          /*
          Auth0 usually returns the folloiwng profile data:
          name - A user name
          nickname - A user nickname (to be displayed when referencing the user)
          picture - A URL to the user's avatar image
          sub - An Auth0 user ID as a string
          updated_at - last date of a profile update (e.g. "2019-09-30T16:34:11.051Z")
           */
          this.authData.userId = profile.sub
          this.authData.userName = profile.name
          this.authData.userNickname = profile.nickname
          ...
```

And does not make further use of the `profile` object as returned by the Auth0 code.

Before investigating further I want to be sure you're using the same version of the code.
Thanks!

**Comment by irina060981** [comment]
Oh, @balmas and @monzug , I am sorry! 
You are right - I missed somehow to update the current webextension code.
It is not up-to-date.

**Comment by irina060981** [comment]
Now authentication works well.
I am really sorry for my absence of mind!
Will close the issue.
