### ISSUE TITLE
LexicalQuery instantiating separate instances of the lexicon client?

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#28]
Haven't fully debugged this yet, but I think with the switch to use of the lexical-query class for lexicon lookups we might have introduced a performance degradation. current design of the lexicon client is to parse the indexes and id files (which it retrieves from a remote server, currently github but eventually the lexicon service) with the first lookup request only and then to reuse this for subsequent requests. If client code instantiates a new instance of the lexicon client adapter we end up reading those files with each request. It seems from the debug console that is what is happening now. Need to investigate more thoroughly why still.

**Comment by kirlat** [comment]
Thanks for the information, I will look into that too.

**Comment by kirlat** [comment]
I think this might have been fixed with alpheios-project/lexicon-client@6e125f0348ca970c6ec10aab167d9b62af0da253
