### ISSUE TITLE
add build number to Safari info.plist files

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#281]
The tagged-commit script needs to add the version and build number to the Safari info.plist files

The version should be used as the value of the CFBundleShortVersionString key and the build number as the value of the CFBundleVersion key

Apply only accepts an integer in these fields so it cannot include the branch name.

**Comment by kirlat** [comment]
This has been merged into `master`.

**Comment by balmas** [comment]
this is working well in Alpheios Reading Tools 3.1.0 build qa.20200513448
