### ISSUE TITLE
support sign-in with Apple for Safari extension

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#283]
I'm pretty sure we won't pass the App store review without this now

https://auth0.com/docs/connections/social/apple

**Comment by kirlat** [comment]
It is working, finally. The Auth0 universal login form customization that we had prevented a "Sign in with Apple" button to appear. Because of this, I removed customization temporarily.

We basically has two versions of universal login available. The first one is "Classic", the same page we've used before. This is how it looks without customization (we could make it shorter if we would like to):

![image](https://user-images.githubusercontent.com/18631055/81169877-adb8c080-8faa-11ea-9b09-31d11b91d14a.png)

The second one is "New":

![image](https://user-images.githubusercontent.com/18631055/81170183-48b19a80-8fab-11ea-8847-22e44f21e4d6.png)

Both works, and I'm not sure what is the better choice in our case. Here is what docs say about functional differencies between them:
> The key structural difference with the Classic Experience is that while the former uses Javascript widgets in all the pages, the New Experience is rendered on the server and does not require Javascript.

> From a functional perspective, it has much better support for Localization, a better MFA experience, and several improvements across all pages. The New Experience is being actively developed, so new features are regularly added. However, there is still a feature gap with the Classic Experience, and some pages in the New Experience have certain differences detailed below.

From how I've read it, a "New" experience is more lightweight, does not require lock.js, and this is where Auth0 put its efforts currently:
> Given that it is being used by a significant percentage of Auth0 customers, the Classic Universal Login Experience will be maintained for the foreseeable future. However, the majority of significant new feature development will be done on the New Universal Login Experience.

But some features of the "Classic" experience are missing; what may be important for us is that the "New" login page cannot be customized: https://auth0.com/docs/universal-login/new-experience-limitations. But, on my opinion, the "New" login form looks good enough.

Which one is better to use? What do you think? Do we need  a login form customization?

**Comment by kirlat** [comment]
I liked that the Auth0 login form integrates with a Keychain Access on Mac. It is enough to enter a Mac account password and Apple ID credentials will be retrieved automatically.

**Comment by kirlat** [comment]
Another thing that I've noticed (but maybe it's just my particular case) is that buttons of Safari App extensions (I have an Alpheios and an another one installed for testing) jump all over the toolbar. They can be together at the left of a URL bar, after a while they may be together at the right of it, then one at the left and another one at the right. I've seen them moving to all possible locations. Here is what I have now. The other plugin's button is at the left of a URL bar, and an Alpheios is at the far right, among other buttons:
![image](https://user-images.githubusercontent.com/18631055/81171907-50267300-8fae-11ea-8629-a50c0a6819f8.png)

This behavior is not specific to Alpheios, the button of the other plugin moves randomly too. Not sure what is causing this behavior and if it is specific to just my system, but I think it might be important to pay attention to it. I will not be surprised if Safari has bugs other than a synthetic click.

**Comment by balmas** [comment]
>But some features of the "Classic" experience are missing; what may be important for us is that the "New" login page cannot be customized: https://auth0.com/docs/universal-login/new-experience-limitations. But, on my opinion, the "New" login form looks good enough.
Which one is better to use? What do you think? Do we need a login form customization?

I think the new one looks ok in the above screenshot. I am fine with going with that if there isn't anything else functionally that we are losing.

**Comment by balmas** [comment]
>This behavior is not specific to Alpheios, the button of the other plugin moves randomly too. Not sure what is causing this behavior and if it is specific to just my system, but I think it might be important to pay attention to it. I will not be surprised if Safari has bugs other than a synthetic click.

Let's enter a separate issue for this so that we can keep track of it and at at least document it in the FAQ

**Comment by kirlat** [comment]
> I think the new one looks ok in the above screenshot. I am fine with going with that if there isn't anything else functionally that we are losing.

I did not discover any issues with the new login during my testing. I will then go ahead and issue a PR.

**Comment by kirlat** [comment]
> Let's enter a separate issue for this so that we can keep track of it and at at least document it in the FAQ

I will enter an issue for that.

**Comment by kirlat** [comment]
This has been merged into `master`.

**Comment by balmas** [comment]
we should try to use the custom login form with this because we need to support the accept terms feature which isn't available in the other version.  

This will require upgrading lock see alpheios-project/alpheios-core#306

**Comment by kirlat** [comment]
I've updated Lock to the latest version (11.23.1) and it is showing a Sign-in with Apple button correctly now.

**Comment by balmas** [comment]
@monzug this change is actually live now because we don't have a separate dev environment for our login form.

Can you do some testing on logins sooner rather than later, using first the released version of the extensions (all 3 browsers) and the texts.alpheios.net environment?  For both this issue and #284  ?

**Comment by monzug** [comment]
tested in Chrome in text env: existing user, sign in with Google, sign in with Apple, not existing user, sign up with existing id, sign up as new user.
question on Apple sign in: I chose to hide my nickname, so the nickname in Alpheios is generating by the system. is there a way to change this option to show my nickname in Alpheios again?

**Comment by kirlat** [comment]
Great, thanks!

> question on Apple sign in: I chose to hide my nickname, so the nickname in Alpheios is generating by the system. is there a way to change this option to show my nickname in Alpheios again?

I'm not sure, not a big user of Apple's. Will read about it.

**Comment by monzug** [comment]
me neither...

**Comment by monzug** [comment]
test the login on texts.alpheios.net (including sign up with Apple) in Firefox and Safari - as Kirlat said, I could not find any issues. will do more testing on the released version

**Comment by monzug** [comment]
I am having some issues with Safari release, note the text env in Safari worked well.
when I logged in and then I logged out, the next time I click on sign in (no matter if I signed in with Apple or Google or any existing user), it does log me in automatically.

**Comment by balmas** [comment]
thanks @monzug . What version of Safari and Mac OS are you running?

**Comment by monzug** [comment]
Safari Version 13.1 (13609.1.20.111.8)
MacOS High Sierra version 10.13.6 (13609.1.20.111.8)

**Comment by monzug** [comment]
I still have to test release on Firefox

**Comment by balmas** [comment]
The display looks okay for me on macOS Catalina 10.15.4 and I would not be very surprised at all if that is a Mac OS issue because the screens look entirely different on Catalina:

![Screenshot 2020-05-07 12 03 40](https://user-images.githubusercontent.com/644870/81317764-41e26080-905b-11ea-96b7-38788277f727.png)

![Screenshot 2020-05-07 12 03 31](https://user-images.githubusercontent.com/644870/81317853-61798900-905b-11ea-8617-a8c53a83d198.png)

**Comment by kirlat** [comment]
> when I logged in and then I logged out, the next time I click on sign in (no matter if I signed in with Apple or Google or any existing user previously), it does log me in automatically.

I think this probably how Auth0 works: once the user is logged in, it caches it credentials in cookie or local storage and while session is not expired (it probably uses a session duration from config settings) it logs the user in automatically.

Probably this is a result of updates of Auth0 scripts.

**Comment by balmas** [comment]
Re the login/logout/login though, I CAN reproduce that.  I need to search if that is already a known issue though. It might be.

**Comment by balmas** [comment]
>Probably this is a result of updates of Auth0 scripts.

@kirlat can you investigate that?

**Comment by kirlat** [comment]
> @kirlat can you investigate that?

Sure, I will.

**Comment by kirlat** [comment]
> when I logged in and then I logged out, the next time I click on sign in (no matter if I signed in with Apple or Google or any existing user previously), it does log me in automatically.

@monzug, to verify the cause of this, can you please do the following in Safari?
1. Log in
2. Log out
3. Go to Safari - Preferences - Privacy, click on "Manage website data" and press "Remove all".
4. Check if it will log you in automatically after that.

**Comment by monzug** [comment]
still I am logged in automatically. I did only try with an existing user
from the list though.

**Comment by kirlat** [comment]
> still I am logged in automatically.

Hmm, I did a test on my platform (Safari 13.1/ macOS 10.15.4) and it is working as expected. We have a max age parameter (an amount of time after authentication when it will require user to re-authenticate) equal to 60 seconds. So if I log in, log out, wait for 60 seconds, and then log in again, it will ask for a password. If I log in, log out, then log in again WITHI the 60 seconds, I will be logged in automatically.

@balmas, can you please check how it is for you?

**Comment by monzug** [comment]
is this a Safari parameter? I did test the text env on Safari and it worked
perfectly, so did Chrome (not Firefox though but for other reasons)

**Comment by kirlat** [comment]
> is this a Safari parameter?

It should be the same for all platforms (i.e. the 60 seconds duration), but for FF and Chrome (no matter what OS it is) we're using an Auth0 Chrome library. For Safari, however, we're using an Auth0 SPA library, so that's different. But the timeout duration should be the same.

If you're in a text environment (alpheios.net) then it uses an embeded library, even on Safari, and it will use an Auth0Lock external script that is loaded onto that page so that's different. It may also have a different timeout set by the page (@balmas please correct me if I'm wrong).

To do a clean test of Auth0 SPA on Safari you have to use a page that has no embedded library in it. I was using https://penelope.uchicago.edu/Thayer/L/Roman/Texts/Pliny_the_Elder/praefatio*.html and Safari App extension login timeout worked for me.

To test a sign in with Apple that we've enabled in Auth0, it has to be working in any environment (ideally).

**Comment by kirlat** [comment]
We just have to support several authentication configurations for multiple platforms 🙁.

**Comment by balmas** [comment]
There are these variations:

1) texts.alpheios.net which uses a server-side authentication flow with Auth0
2) the webextension on Firefox and Chrome (regardless of OS) which uses the WebAuthenticationAPI for for the authentication flow with Auth0
3) the safari app extension on Safari/Mac which uses the SPA (single page app) authentication flow with Auth0

All 3 of these use the same login form, but the way the authentication parameters are passed and set differs.

Upon explicit logout, the request should be made to the Auth0 service to log the user out and invalidate any Auth0 cookie, so I don't think the session timeouts should be coming in to play here (they do in the case of a timed out session, but that is a separate issue).

@kirlat I believe the Safari app extension uses the SPA logout() method to log out of the Auth0 session. The release version of the Safari App Extension is using a pretty old version of the spa library and maybe that's the difference here? Are you using a new build of the Safair App Extension (i.e. one with the newer SPA library or the release version)?

**Comment by balmas** [comment]
> > still I am logged in automatically.
> 
> Hmm, I did a test on my platform (Safari 13.1/ macOS 10.15.4) and it is working as expected. We have a max age parameter (an amount of time after authentication when it will require user to re-authenticate) equal to 60 seconds. So if I log in, log out, wait for 60 seconds, and then log in again, it will ask for a password. If I log in, log out, then log in again WITHI the 60 seconds, I will be logged in automatically.
> 
> @balmas, can you please check how it is for you?

I don't think this is the right behavior actually. When we logout explicitly, it should not matter what the timeout is.

**Comment by kirlat** [comment]
> I don't think this is the right behavior actually. When we logout explicitly, it should not matter what the timeout is.

Here is a description of a `max_age` parameter: https://auth0.github.io/auth0-spa-js/interfaces/popuploginoptions.html#max_age.
This [document](https://auth0.com/docs/sessions/concepts/session-lifetime) provides some additional explanation. I think `max_age` is the same as a parameter called `Require log in after` in a text: https://auth0.com/docs/sessions/concepts/session-lifetime#examples-session-lifetime-limits.

I understand it as: if a user is within a `max_age` limit, he or she will never be asked to re-authenticate. So even if she or he logged out, but then logged in again within a limit set by a `max_age`, she or he will be logged in without asking for password.

Do you have the same understanding?

In that case, if we want user to be logged out without absolutely no ability to log in with no password entered, we should set its value to zero. What do you think?

**Comment by balmas** [comment]
I still think we're talking about 2 different things.

As I understand it, max_age has to do with how long the user can stay logged in if they haven't explicitly chosen to logout, i.e. how long before we expire their session. I don't think we ever want to force-expire their session if they haven't explicitly chosen to logout.

However, if they choose to logout, then we should use the Auth0 api to log them out of their session explicitly, in which case the max_age is irrelevant.

**Comment by kirlat** [comment]
I've checked the source code and it seems that a `max_age` is related to the authentication period while session expiration period is handled via an `expDate`: https://github.com/auth0/auth0-spa-js/blob/3285b24db85786039fb681ecd0c2bd6988afc89e/src/jwt.ts#L162-L187
I can't find any explanation of a `max_age` that is clear enough, but from my testing I has an impression it has something to do with whether to show a login popup or authenticate silently, if there is an unexpired token.

**Comment by balmas** [comment]
ah, you might be right. This could be something that affects how long an id token can used which is something different than session expiration.  If so, then a max_age of something like 2 minutes might make sense. What do you think @kirlat ?

**Comment by kirlat** [comment]
If it is a machine used by a single person only, long max age is very convenient: it allows to login without entering a password. On the other hand, if computer is shared, we want to have it at a minimum to reduce security risks.

In the future, if we want, we could probably add something like a "remember password on this machine" option that, when on, will set a long max age period. Users who do not share their computers with other can set this option and enjoy a luxury of not entering a password often. All other users, on the other hand, will get security of a short max age duration.

What do you think?

Since the US National Institute of Standards and Technology recommends 2 to 5 minutes inactivity timeouts (https://auth0.com/blog/when-ux-equals-keeping-or-losing-the-customer/) I think two minutes is the best choice. Should I make a PR to update max age in config files?

**Comment by balmas** [comment]
> Should I make a PR to update max age in config files?
Yes please.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.1.0 build qa.20200513448

Need to include Authentication as part of regressions of the new release of the Safari App Extension.

**Comment by monzug** [comment]
tested in Safari App extension 3.1.0 build qa.20200513448
after 2 minutes, I am prompt to login again. Thanks.
