### ISSUE TITLE
Wandering extension buttons in Safari

### ISSUE THREAD

**Issue by kirlat** [alpheios-project/webextension#285]
During testing on Safari that I've noticed (but maybe it's just my particular case) that buttons of Safari App extensions (I have an Alpheios and an another one installed for testing) jump all over the toolbar. They can be together at the left of a URL bar, after a while they may be together at the right of it, then one at the left and another one at the right. I've seen them moving to all possible locations. Here is what I have now. The other plugin's button is at the left of a URL bar, and an Alpheios is at the far right, among other buttons:
![image](https://user-images.githubusercontent.com/18631055/81171907-50267300-8fae-11ea-8629-a50c0a6819f8.png)

This behavior is not specific to Alpheios, the button of the other plugin moves randomly too. Not sure what is causing this behavior and if it is specific to just my system, but I think it might be important to pay attention to it. I'm wondering how reproducible it will be on other machines, I think it needs further verification.

**Comment by balmas** [comment]
@monzug something to be aware of when testing the Safari app extension.

**Comment by monzug** [comment]
I haven't seen it but I will definitely pay more attention to the alpheios icon during regression

**Comment by kirlat** [comment]
I've updated macOS to 10.15.5 recently and I has not seen since then. So maybe that was a Safari bug that was fixed in the latest release. But I did test it long enough to be certain.

**Comment by monzug** [comment]
Thanks for the update!

**Comment by monzug** [comment]
my mac is High Sierra 10.13.6

**Comment by monzug** [comment]
I haven't seen it also on Catalina
