### ISSUE TITLE
Safari: prompt for Google account

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#294]
> @balmas, I have a question: when I sign in with Google in Safari, it does not prompt for id/psw. I am logged in automatically, and I waited for more than 2 minutes too. In Chrome (Mac/PC), it does prompt for id/psw initially, then in any subsequent attempt, I select the user and then I am automatically logged in. why in Safari I do not get the prompt for id? even if I chose to save id/psw automatically, shouldn't it prompt for which user I want to log in with? what if I want to login as a different user?

Yes it should. I think we may need to just tweak a setting in the Safari Login configuration for this.  I'll convert this to a new issue.

_Originally posted by @balmas in https://github.com/alpheios-project/webextension/issues/266#issuecomment-637570989_

**Comment by balmas** [comment]
Kirill I am fairly certain this is a configuration setting somewhere ....

**Comment by balmas** [comment]
the two minutes is probably the max_age timeout.

The issue here though, I believe, is with multiple Google accounts. I.e if you try to login with different Google user accounts you aren't allowed. We had the this same issue with the webextension: https://github.com/alpheios-project/components/issues/444 we had to include the following in the parameters to solve it

```
        params: { prompt: 'select_account' }
```

**Comment by kirlat** [comment]
A fix has been merged into master.

**Comment by balmas** [comment]
Alpheios Reading Tools 3.3.0 build qa.20200605325
Alpheios Components 3.3.0-qa.20200605311

**Comment by monzug** [comment]
tested login with Google in Safari and it does prompt for which user I want to login
