### ISSUE TITLE
Chinese word at the top of most recent limit

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#296]
I applied the limit to most recent to a wordlist that I have been using for testing all day. I noticed that this limit has a Chinese word at the top while I expected to see the words added in current session. the Chinese word was indeed added today too but few sessions before the two other Latin words with the current session icon (paterentur et laborum). Note that normally with Greek and Latin words the limit works by listing the most recent words in wordlist. not sure what's going on here
see screenshot
![most-recent](https://user-images.githubusercontent.com/41396793/84790878-decfdc00-afbf-11ea-99db-6f7431eb66cb.JPG)

**Comment by balmas** [comment]
hmm. was it possibly added with a different computer set to a different timezone?

**Comment by monzug** [comment]
yes, it could be. let me try with a greek word then

**Comment by monzug** [comment]
so glad this is not an issue! Thanks Bridget for the suggestion

![most-recent-from mac](https://user-images.githubusercontent.com/41396793/84795523-9d422f80-afc5-11ea-85db-0a04db5dffed.JPG)
