### ISSUE TITLE
need an embeddable ui component for alpheios results

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#3]
While some parts of the Alpheios UI, such as the infleciton table display, are probably best displayed in a panel, we still want the option to produce an embeddable element which can be displayed in the context of the word the user selected. This should be modeled on the Alpheios popup from the old Firefox extension.

**Comment by kirlat** [comment]
Totally agree, will start working on that.

**Comment by balmas** [comment]
So, just to confirm some of the requirements for this discussed today (and maybe a few others)
1. component should be positioned near the user's interaction with the page, i.e. near the word they clicked on
2. it should be moveable and resizable - user should be able to drag it, close it, enlarge it
3. it should include the information from the homonym object, including a short definition, and the credits to the provider(s) of this information
4. it should contain ui elements (buttons/icons) which user can use to open the alpheios panel with additional resources loaded.. e.g. a icon for the full definitions, an icon for the inflection tables, 
5. it should be possible for the information in the component to be populated in a tab in the alpheios panel instead/in addition
6. the component can appear like a popup but should NOT be an actually popup window. It should be added as an element to the page the user is viewing.- i.e. we don't want the browser to block this.

attaching a screenshot of the original Alpheios popup for reference

![popup](https://user-images.githubusercontent.com/644870/33025316-9c6d301a-cddb-11e7-91f4-08068c82d748.PNG)

**Comment by balmas** [comment]
if we can implement this as a component in a library separate from the extension, that would be ideal -- i.e. I would like for it to be able to be reused by a page-embedded library  -- but it's not an absolute requirement at this stage.

**Comment by balmas** [comment]
this is in place now.
