### ISSUE TITLE
A strange definition ...

### ISSUE THREAD

**Issue by demophobos** [alpheios-project/webextension#315]
![alph_mistake](https://user-images.githubusercontent.com/7735754/100988260-95b91780-3560-11eb-8fa8-bdbd608224ce.png)

**Comment by balmas** [comment]
thank you for finding the issue. We will fix this!

**Comment by balmas** [comment]
should be fixed in now in lsl, middle-liddel, major+ml, major+lsj

verification pending deployment of fixed defs files.

**Comment by balmas** [comment]
@monzug this change has been made in the live lexicon service files.   Please verify whenever you have a chance. Thanks!

**Comment by monzug** [comment]
I tried different combination of the word ἁπιοτοίην,άπιοτοίην,ὰπιοτοίην,ἀπιοτοίην with no results. can't find this word. help

**Comment by balmas** [comment]
ἀπιστοίην

**Comment by monzug** [comment]
Thanks! hard to say what I was typing wrong but something was definitely not right.

**Comment by monzug** [comment]
LSJ and major+LSJ   have disbelieve, distrust
Middle Liddell and Major+ml have disbelieve, distrust, mistrust
is it ok or do they have to match?

**Comment by balmas** [comment]
these are differences (albeit minor) in the definitions from LSJ and ML so I left that as is. I think it's ok.

**Comment by monzug** [comment]
all good for me.
