### ISSUE TITLE
Gradus abest

### ISSUE THREAD

**Issue by demophobos** [alpheios-project/webextension#316]
![alpheios_project_issue_002](https://user-images.githubusercontent.com/7735754/101764543-3bd0c880-3af1-11eb-87d0-7a19552e8acb.png)

**Comment by balmas** [comment]
it looks like the issue is that we just take the first sense from the lexicon, "single" for the short definition and it would probably be better to extend this to e.g. "single, simple straightforward".

**Comment by balmas** [comment]
@monzug this change has been made in the live lexicon service files.   Please verify whenever you have a chance. Thanks!

**Comment by demophobos** [comment]
> it looks like the issue is that we just take the first sense from the lexicon, "single" for the short definition and it would probably be better to extend this to e.g. "single, simple straightforward".

It's not about the sense, it's about the degree of comparison of the adjective, which should be presented in the form definition.
Like you do in similar cases:
![image](https://user-images.githubusercontent.com/7735754/101799425-32f5ec00-3b1d-11eb-945c-3aa37017a3cc.png)

**Comment by balmas** [comment]
ah, ok, thanks for the clarification.  I think the short definition benefited from the attention anyway :-)

Regarding the comparative, the parser reports this form differently (as an irregular comparative), which we weren't catching. We'll put that fix on the list for an upcoming release. Thank you!

**Comment by monzug** [comment]
ἁπλόος is single, simple, straightforward

However in Major+LSJ   and  LSJ it's twofold. see below

![Screen Shot 2020-12-11 at 4 01 11 PM](https://user-images.githubusercontent.com/41396793/101919193-90944200-3bca-11eb-84b9-1dc2d15b7b7c.png)

**Comment by balmas** [comment]
I've updated this short def everywhere now.

**Comment by monzug** [comment]
short def for ἁπλόος  is  single, simple   in  Logeion
short def for  ἁπλόος  is single, simple straightforward in Major+LSJ, Liddell, Liddell Scott Jones
No definition found in Dodson, Abbott-Smith and Homeric Lexicon
