### ISSUE TITLE
Firefox: Action Required: Add-on Policy Changes

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/webextension#325]
<div style="height:100%;word-break:break-word;font-size:16px;font-weight:normal;background-color:transparent;line-height:1;font-family:Arial,Helvetica,sans-serif">
                                                          <p><span style="background-color:transparent">Hello,</span></p>
                                                          <div>&nbsp;<br>
                                                          </div>
                                                          <p><span style="background-color:transparent">You
                                                          are receiving
                                                          this email
                                                          because you
                                                          are listed as
                                                          the developer
                                                          of an
                                                          extension for
                                                          Firefox.</span></p>
                                                          <div>&nbsp;<br>
                                                          </div>
                                                          <p><span style="background-color:transparent">We
                                                          will be </span><a href="https://links.email.mozilla.org/els/v2/vpALQ6KEqSY/QnFuczFZa3VQQUc3YmxoenRScUpCS0owbGFmbTZxK2pNWHk3NHgvK1V6eEhla1hScWxRaUg0L0x3S2FxRGplY0xmQmwwc21LZXVXYll4V3BySlYxZnc9PQS2/" name="m_-4677004681958679137_m_-394435981682424608_m_7103349293098853941_m_5375960222828152694_m_-4934630923557653757_blog_policy_change" rel="noopener
                                                          noreferrer
                                                          noopener
                                                          noreferrer" style="color:rgb(0,104,255);text-decoration:none" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://links.email.mozilla.org/els/v2/vpALQ6KEqSY/QnFuczFZa3VQQUc3YmxoenRScUpCS0owbGFmbTZxK2pNWHk3NHgvK1V6eEhla1hScWxRaUg0L0x3S2FxRGplY0xmQmwwc21LZXVXYll4V3BySlYxZnc9PQS2/&amp;source=gmail&amp;ust=1637138897549000&amp;usg=AOvVaw35rdUJDB1AvpplCv_eDa6q">updating our add-on policies</a><span style="background-color:transparent"> <strong>effective December 1st,
                                                          2021</strong>.
                                                          To summarize
                                                          the changes
                                                          that will go
                                                          into effect:</span></p>
                                                          <div>&nbsp;<br>
                                                          </div>
                                                          <ul>
                                                          <li><span style="background-color:transparent">We
                                                          will <strong>no
                                                          longer be
                                                          accepting</strong>
                                                          the collection
                                                          of browsing
                                                          activity data,
                                                          unless it is
                                                          part of the
                                                          add-on’s
                                                          primary
                                                          function.</span></li>
                                                          <li><span style="background-color:transparent">Add-ons
                                                          with the sole
                                                          purpose of
                                                          promoting,
                                                          installing,
                                                          loading or
                                                          launching
                                                          another
                                                          website,
                                                          application or
                                                          add-on are<strong>
                                                          no longer
                                                          permitted</strong>
                                                          to be listed
                                                          on <a href="http://addons.mozilla.org/" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://addons.mozilla.org/&amp;source=gmail&amp;ust=1637138897549000&amp;usg=AOvVaw1d4yRC23lwoNHyx927yF32">addons.mozilla.org</a>.</span></li>
                                                          <li><span style="background-color:transparent">The
                                                          use of
                                                          encryption -
                                                          standard HTTPS
                                                          - is now
                                                          always
                                                          required when
                                                          communicating
                                                          with remote
                                                          services.</span></li>
                                                          </ul>
                                                          <p><span style="background-color:transparent">We
                                                          have also
                                                          updated the
                                                          language
                                                          regarding the
                                                          data
                                                          disclosure,
                                                          collection and
                                                          management. If
                                                          your add-on
                                                          does not have
                                                          a privacy
                                                          policy listed
                                                          on <a href="http://addons.mozilla.org/" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://addons.mozilla.org/&amp;source=gmail&amp;ust=1637138897549000&amp;usg=AOvVaw1d4yRC23lwoNHyx927yF32">addons.mozilla.org</a>, or your
                                                          add-on does
                                                          not show a
                                                          consent prompt
                                                          at first run
                                                          of the add-on,
                                                          we encourage
                                                          you to read
                                                          our updated
                                                          policies and
                                                          take action as
                                                          necessary.</span></p>
                                                          <div>&nbsp;<br>
                                                          </div>
                                                          <p><span style="background-color:transparent">When
                                                          the policies
                                                          go into
                                                          effect, they
                                                          apply both to
                                                          existing and
                                                          future
                                                          submissions on
                                                          <a href="http://addons.mozilla.org/" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://addons.mozilla.org/&amp;source=gmail&amp;ust=1637138897549000&amp;usg=AOvVaw1d4yRC23lwoNHyx927yF32">addons.mozilla.org</a>.&nbsp;</span></p>
                                                          <div>&nbsp;<br>
                                                          </div>
                                                          <p><span style="background-color:transparent">You
                                                          can </span><a href="https://links.email.mozilla.org/els/v2/dpANQ2RLGhY/QnFuczFZa3VQQUc3YmxoenRScUpCS0owbGFmbTZxK2pNWHk3NHgvK1V6eEhla1hScWxRaUg0L0x3S2FxRGplY0xmQmwwc21LZXVXYll4V3BySlYxZnc9PQS2/" name="m_-4677004681958679137_m_-394435981682424608_m_7103349293098853941_m_5375960222828152694_m_-4934630923557653757_policy_preview" rel="noopener
                                                          noreferrer
                                                          noopener
                                                          noreferrer" style="color:rgb(0,104,255);text-decoration:none" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://links.email.mozilla.org/els/v2/dpANQ2RLGhY/QnFuczFZa3VQQUc3YmxoenRScUpCS0owbGFmbTZxK2pNWHk3NHgvK1V6eEhla1hScWxRaUg0L0x3S2FxRGplY0xmQmwwc21LZXVXYll4V3BySlYxZnc9PQS2/&amp;source=gmail&amp;ust=1637138897549000&amp;usg=AOvVaw19JpOSTvnM9qVWYTDEK6zP">preview the policy</a><span style="background-color:transparent">
                                                          and ensure
                                                          your
                                                          extensions
                                                          abide by them
                                                          to avoid any
                                                          disruption.</span></p>
                                                          <div>&nbsp;<br>
                                                          </div>
                                                          <p><span style="background-color:transparent">Thank
                                                          you for your
                                                          help in
                                                          keeping the
                                                          add-ons
                                                          ecosystem
                                                          safe. If you
                                                          have questions
                                                          about these
                                                          updated
                                                          policies or
                                                          would like to
                                                          provide
                                                          feedback,
                                                          please post to
                                                          </span><a href="https://links.email.mozilla.org/els/v2/xdAYQrxgZSr/QnFuczFZa3VQQUc3YmxoenRScUpCS0owbGFmbTZxK2pNWHk3NHgvK1V6eEhla1hScWxRaUg0L0x3S2FxRGplY0xmQmwwc21LZXVXYll4V3BySlYxZnc9PQS2/" name="m_-4677004681958679137_m_-394435981682424608_m_7103349293098853941_m_5375960222828152694_m_-4934630923557653757_discourse" rel="noopener
                                                          noreferrer
                                                          noopener
                                                          noreferrer" style="color:rgb(0,104,255);text-decoration:none" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://links.email.mozilla.org/els/v2/xdAYQrxgZSr/QnFuczFZa3VQQUc3YmxoenRScUpCS0owbGFmbTZxK2pNWHk3NHgvK1V6eEhla1hScWxRaUg0L0x3S2FxRGplY0xmQmwwc21LZXVXYll4V3BySlYxZnc9PQS2/&amp;source=gmail&amp;ust=1637138897549000&amp;usg=AOvVaw0hK1wc9IHmOQ_WmYjRqCxD">this thread</a><span style="background-color:transparent">
                                                          in our
                                                          community
                                                          forum.</span></p>
                                                          <div>&nbsp;<br>
                                                          </div>
                                                          <p><span style="background-color:transparent">Regards,</span></p>
                                                          <div>&nbsp;<br>
                                                          </div>
                                                          <p><span style="background-color:transparent">The
                                                          Add-ons Team</span></p>
                                                          <p><span style="background-color:transparent"><a href="http://addons.mozilla.org/" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://addons.mozilla.org/&amp;source=gmail&amp;ust=1637138897549000&amp;usg=AOvVaw1d4yRC23lwoNHyx927yF32">addons.mozilla.org</a></span></p>
                                                          </div>

**Comment by irina060981** [comment]
> We will no longer be accepting the collection of browsing activity data, unless it is part of the add-on’s primary function.
> We don't collect browsing activity data  - if it means reading history, checking urls of other tabs
> 

**from @irina060981** 
the only problem here that for some reasons we have to get these permissions from a user.
But I don't remember why do we have them.

**from @balmas** 
I don’t remember either.  We could try removing the permission and having Monica do a full regression test, and if everything works, then not worry about it.  

>Add-ons with the sole purpose of promoting, installing, loading or launching another website, application or add-on are no longer permitted to be listed on addons.mozilla.org.
>

**from @irina060981** 
We have activities - launching other site for using chinese vocabulary for translating in an iframe, but it couldn't be named as the sole purpose.

**from @balmas** 
I agree

>The use of encryption - standard HTTPS - is now always required when communicating with remote services.
>

**from @irina060981** 
I found one place that should be checked:
  - DefaultSiteOptions has the following treebank links:
```
          "treebanks": {
            "labelText": "Treebanks",
            "defaultValue": "http://alpheios.net/alpheios-treebanks/tbext.html?owner=perseids-project&repos=harrington_trees&collid=lattb&objid=7229&doc=lattb.7229.1",
            "multiValue": false,
            "values": [
                { "value": "http://alpheios.net/alpheios-treebanks/tbext.html?owner=perseids-project&repos=harrington_trees&collid=lattb&objid=7229&doc=lattb.7229.1",
                  "test": "Example Site Treebank"
                }
              ]
          }
```
But I believe that it could be easily updated to https, because our site is used under https
and also I think this option should not be ever used

**from @balmas** 
We could just remove these settings. They aren’t used.

>We have also updated the language regarding the data disclosure, collection and management. If your add-on does not have a privacy policy listed on addons.mozilla.org, or your add-on does not show a consent prompt at first run of the add-on, we encourage you to read our updated policies and take action as necessary.
>

**from @irina060981** 
I din't find privacy policy listed on https://addons.mozilla.org/ru/firefox/addon/alpheios-reading-tools/
and we don't show any prompt on starting the extension.
But if I understand right - it is not really necessary to have.

**from @balmas** 
We do have one. It’s at http://alpheios.net/pages/privacy-policy/. I was pretty sure I loaded it on the add-ons site, so it’s weird that it’s not there.

**Comment by irina060981** [comment]
>We will no longer be accepting the collection of browsing activity data, unless it is part of the add-on’s primary function.
We don't collect browsing activity data - if it means reading history, checking urls of other tabs

Hope this is fixed

**Comment by irina060981** [comment]
I believe that everything here is fixed (except publishing privacy policy - waiting for credentials)

So you can verify it after regression tests

**Comment by monzug** [comment]
Irina, do you mean that regression test should be enough to verify above fixes or is there any specific testing that I should be doing?

**Comment by irina060981** [comment]
No, there is no specific testing here - all testing is to verify that everything is still working :)

**Comment by monzug** [comment]
Privacy police is in https://addons.mozilla.org/en-US/firefox/addon/alpheios-reading-tools/privacy/

**Comment by irina060981** [comment]
Thank you - I didn't find it myself from user perspective :)

**Comment by monzug** [comment]
regression passed in Alpheios Reading Tools 3.4.1 build incr-3.4.x.20211201209
Alpheios Components 3.3.3-incr-3.4.x.20211125318 build i331-la-lat-update-lang.20211201494
