### ISSUE TITLE
Paideia glossary

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#332]
As I have never used the Paideia glossary before, I just gave it a try in FF/PC  Alpheios Reading Tools 3.4.1 build incr-3.4.x.20211118345
Alpheios Components 3.3.3-incr-3.4.x.20211116233 build i662-lexical-dicts.20211118457 

Few issues here:
1) I think Paideia glossary is the right terminology, so pls change Paidea into Paideia in the Lexicons (Short Definitions) drop-down 
2) when I select the Paideia Glossary and remove the Whitaker, it does work correclty in lookup and wordlist but it does not in double click. It briefly shows a pop-up with Paideia Glossary but then it generated the pop-up from Whitaker. see below

from double click
![paideia-2](https://user-images.githubusercontent.com/41396793/142598423-a9fb0f2e-f2d9-491d-a6f9-43997dc1327a.JPG)

from lookup or wordlist
![paideia](https://user-images.githubusercontent.com/41396793/142598430-25bfb55b-a47e-4398-a4fd-6a73b21cfa96.JPG)

3) this is a question: if I select only Paideia glossary, I was expecting to see onlythis  glossary, and not also the Whitaker which is deselected. how should it work? in the greek language when I deselect all glossaries, I get No definition found. Instead, in the Latin, when no glossary is selected, I still get the definition from Whitaker glossary. it looks like Whitaker is sticky.

**Comment by monzug** [comment]
see https://github.com/alpheios-project/alpheios-core/issues/647

**Comment by monzug** [comment]
actually, after reinstalling FF and latest alpheios build, issues 2 and 3 are not longer reproducible.

**Comment by irina060981** [comment]
Spelling is changed

**Comment by monzug** [comment]
fixed.
