### ISSUE TITLE
the wordlist pop-up is displayed behind morphology pop-up

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#335]
I do not know if this is new or if it has been around for a while, seen FF/Mac in  Alpheios Reading Tools 3.4.1 build incr-3.4.x.20211123265 Alpheios Components 3.3.3-incr-3.4.x.20211123114 build i333-options-reset.20211123556 

if I keep double clicking on greek words when page language is set to latin, the morphology pop-up will say that lexical query produced no results. then when I go to wordlist, the pop-up is open under the morphology pop-up. focus should be on the wordlist pop-up.
see below
![Screen Shot 2021-11-23 at 4 41 53 PM](https://user-images.githubusercontent.com/41396793/143056458-8d1007f6-c3bb-493f-b1ca-fddf2ee94b7e.png)

**Comment by irina060981** [comment]
I was not able to reproduce it. (both on Windows and MacOS)
It is manually in the code defined that panel should be upper (on layers) than popup.
If you could reproduce it - could you screenshot the following:
 - at the same place where you see console - select Inspector tab
 
![image](https://user-images.githubusercontent.com/12377640/143191510-e5776f5e-f6f8-4fa7-83d4-2bc0efad6c01.png)

- panel and popup are attached at the end

- I need the same screenshots as below
  - selected panel
     
![image](https://user-images.githubusercontent.com/12377640/143191601-8544188d-a4aa-4753-a8d9-c1231dc985f8.png)

Z-index is shown at the second part (Z-index defines layer order) - for panel it is 2010

  - selected popup
  
![image](https://user-images.githubusercontent.com/12377640/143191724-ade91817-9287-4d8a-88eb-d2109274c00a.png)

For popup it is 2000

In your case Panel should have less than 2000.
I need screenshots and exact values.

**Comment by monzug** [comment]
I have this screenshot. see if it can be helpful
![Screen Shot 2021-11-24 at 8 52 18 AM](https://user-images.githubusercontent.com/41396793/143197291-39a6aa85-223f-4aec-931a-7fb12f935857.png)

**Comment by monzug** [comment]
z-index is 2011
![Screen Shot 2021-11-24 at 8 56 45 AM](https://user-images.githubusercontent.com/41396793/143197529-194ad77e-bef6-4302-9833-abc2eb00ddf3.png)

**Comment by monzug** [comment]
anyhow, I am not able to reproduce it right now. I took the screenshot this morning from yesterday scenario. After refreshing the page I could not repro it.

**Comment by monzug** [comment]
ok, I just got the wordlist behind the pop-up (what I did: start with greek language and go to wordlist and double click on any words in both latin and greek list, then change page language to latin, double click on few greek words and got the lexical query produced no results pop-up, then go to wordlist and click on any greek words saved under the latin list, wordlist pop-up goes under the last pop-up generated.
![Screen Shot 2021-11-24 at 9 04 47 AM](https://user-images.githubusercontent.com/41396793/143199270-7ade9fc8-2018-48ae-8534-fc3be6e175fb.png)
![Screen Shot 2021-11-24 at 9 06 02 AM](https://user-images.githubusercontent.com/41396793/143199280-7ad7e580-0f36-4924-96ae-181a8205e2fd.png)
![Screen Shot 2021-11-24 at 9 06 16 AM](https://user-images.githubusercontent.com/41396793/143199287-3d228af5-1b5f-49b3-91e4-a3296fa1d864.png)

**Comment by irina060981** [comment]
it is very strange - z-index property is correct

**Comment by irina060981** [comment]
I was able to reproduce it on MAC/FF again - two copies of extension was attached
It creates this mixed

**Comment by monzug** [comment]
I noticed. can u reproduce doing the steps that I did in the last comment?

**Comment by monzug** [comment]
ah ok. is it only FF/MAC? we should check if it 's worth fixing it based on
how many users are on FF/Mac.

**Comment by irina060981** [comment]
it is strange - I will recheck.

**Comment by irina060981** [comment]
I was able to reproduce it only on Mac/Firefox - it was not easy to reproduce - I clicked many times.
But for now I completely does not understand how it could happen from code perspective.
Will need more specific investigation.

**Comment by irina060981** [comment]
I found the bug - it could be reproduced on any browser.
We upload content (when reload) when the tab catches event that page loading process is complete. (it is our new workflow for removing permissions).
But it turned out that a tab gets loading is complete two times - full complete and very full complete (I don't know what is the exact difference but it seems to me that the second emitts when all page resources are loaded).

Anyway I prevent from loading content on the lateter loaded event.
So we should not have multiple popups now.

**Comment by monzug** [comment]
Brava!!!! so glad you found a fix. Thanks

**Comment by monzug** [comment]
this is not longer reproducible in  Alpheios Reading Tools 3.4.1 build incr-3.4.x.20211125333
Alpheios Components 3.3.3-incr-3.4.x.20211123271 build ext-i323-message.20211125609

**Comment by monzug** [comment]
to retest in chrome

**Comment by monzug** [comment]
Chrome/PC and Mac on Alpheios Reading Tools 3.4.1 build incr-3.4.x.20211201209
Alpheios Components 3.3.3-incr-3.4.x.20211125318 build i331-la-lat-update-lang.20211201494
