### ISSUE TITLE
Regression on FF: right position and maximum pop-up width do not seem to work

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#337]
regression on options in FF. I noticed that the maximum width of the pop-up does not seem to work as well as it did in the release. also Panel position sets to right does not work, it worked indeed in the release.

**Comment by irina060981** [comment]
Monica, I was not able to reproduce panel problem.
For me on Firefox:

- panel position by clicking move panel to right/left icon
   
![image](https://user-images.githubusercontent.com/12377640/143984008-7cc96d8b-57b1-4e6b-8df3-0a01add0d52f.png)

![image](https://user-images.githubusercontent.com/12377640/143984030-5ae5950c-0885-435f-a646-12c457ffce14.png)

what do you mean saying - 
> the maximum width of the pop-up does not seem to work as well as it did in the release

Give me more details please

**Comment by monzug** [comment]
will reinstall the latest build again. the enlargement of the pop-up based
on the setting maximum width of the pop-up did not enlarge the pop-up. will
try again with new installation and get back to you. Thanks

**Comment by monzug** [comment]
I clear cache and reinstall the latest build. I still see the problem with panel position set to right that does not do anything. the arrows to move left and right work perfectly. it's the setting that does not take action properly. see screenshots
![Screen Shot 2021-11-30 at 9 05 52 AM](https://user-images.githubusercontent.com/41396793/144009646-2d58add7-41ec-4467-bce6-7e98f0172cae.png)
![Screen Shot 2021-11-30 at 9 06 06 AM](https://user-images.githubusercontent.com/41396793/144009653-47cc7ac5-8f9a-408b-9f0f-8a2d4ff0e295.png)

**Comment by monzug** [comment]
I'll try on FF/PC again with latest build.

**Comment by irina060981** [comment]
About panel position - oh I see what do you mean.
It does not change position on setting change (in Firefox and Chrome), only on icon clicking.
I will check it

**Comment by irina060981** [comment]
>Not sure how it should work.

Then how does it work in previous release if you are sure - it worked before?

**Comment by monzug** [comment]
same in FF/PC. it looks like it works only on first install, e.g. if panel position is set to right then panels will open on right. will check again against the latest release from January. I thought I could move the panel by changing the settings but that's what the arrows are for!!! 
how about the maximum width? it works as medium for me. will check against release

**Comment by monzug** [comment]
ok, it works as in the release so it's a non issue.

**Comment by monzug** [comment]
> > Not sure how it should work.
> 
> Then how does it work in previous release if you are sure - it worked before?

I searched github to see if there were any info about it but could not find. it has been a while and I really do not remember how it should work. anyhow it's same in latest release so good enough.

**Comment by monzug** [comment]
Thanks irina , you are so right. I am almost done with regression and so
far so good.
