### ISSUE TITLE
i-mus: it's not highlighted in the inflection table. why?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#338]
this is in the release and also in latest build, so it's not relevant but I wondering why I do not get an exact match like for the adjective.
go to https://www.tradurreantico.it/latino/grammatica-latina/morfologia/verbo/verbo-eo-latino/ and double click on i-mus. pop-up says that it's an adjective and  a verb. go to inflection table, the adjective has a match that is highlighted in yellow. instead the verb does not have any match in the inflection table. why?
the same in lookup. if I remove the dash, I have the exact match.
![imus](https://user-images.githubusercontent.com/41396793/144040600-b6fe01e1-7cab-46b7-92c6-312db7669a5b.JPG)

**Comment by irina060981** [comment]
I believe that the main problem - that there is no match here.
If we lookup the following - there would be exact much:
`īmus`
![image](https://user-images.githubusercontent.com/12377640/144219017-f6f49721-35cc-4069-b84e-c3aff4deecde.png)

`iimus`
![image](https://user-images.githubusercontent.com/12377640/144219505-556cc8d5-5b17-4737-a532-8cd8103d5135.png)

what exactly should be highlighted in the verb irregular table for `i-mus`?

**Comment by monzug** [comment]
should be the indicative active 1st person plural, same as imus - at least
I was expecting a blue highlighted.

**Comment by irina060981** [comment]
As I could see from the code
 - blue highlignting is for suffix match
 - yellow highlighting is for full match
 
There is no support in the code for suffix match in irregular verbs, so you won't see any blue highlighting in irregular verbs table.
So I could not improve anything here without some global changes for requirements.
Do you have any questions here? Or we could close this issue?

**Comment by monzug** [comment]
please close. thanks
