### ISSUE TITLE
tooltip are hidden by the browsing inflection tables

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#339]
FF/mac and PC. also in release, so it's not important. see attachment
![Screen Shot 2021-11-30 at 2 30 30 PM](https://user-images.githubusercontent.com/41396793/144056304-1c2ce985-155d-4f7d-bd9d-6476e334eb3a.png)

**Comment by irina060981** [comment]
Fixed in new release

**Comment by monzug** [comment]
Fixed. Thanks
