### ISSUE TITLE
Whitaker is sticky in short definitions

### ISSUE THREAD

**Issue by monzug** [alpheios-project/webextension#340]
I remove all Lexicons (short definitions) from Latin and Greek. In Greek, I get no definition found on any double click. in Latin, I still get the Whitaker short definitions.
see comment from issue #332 - see below

 in the greek language when I deselect all glossaries, I get No definition found. Instead, in the Latin, when no glossary is selected, I still get the definition from Whitaker glossary. it looks like Whitaker is sticky.

![Screen Shot 2021-11-30 at 3 06 43 PM](https://user-images.githubusercontent.com/41396793/144062139-8f3529c7-1e95-48a7-819c-98aef941daca.png)
![Screen Shot 2021-11-30 at 3 05 41 PM](https://user-images.githubusercontent.com/41396793/144062145-fa653504-4744-48a2-8400-49cc1c3529a6.png)

**Comment by irina060981** [comment]
Yes, It is true - Whitaker short definitions are sticky.
How it works - we get whhitaker's definitions with morphology data in the same request.
And before Paidea we didn't have any ability to select another short definitions dictionary for Latin.

When we get a task to add an ability to see only Paideia definitions - I updated a workflow the following way:
- an application gets morphology + Whitaker definitions
- checks if we have selected Paidea, if true - an application clears Whitaker definitions and requests for Paidea definitions

In your case - it checks, doesn't see other dictionaries - and doesn't do anything (not clear. not additional request)

We discussed this behaviour before with Harry , I believe.

Anyway if we want to clear Whitaker definitions when Short definitions option is empty we need to define it as a requirement.

**Comment by monzug** [comment]
an easy workaround (not pretty, though) is to remove pick one from drop-down. I can have whitaker, I can have paideia glossary, I can have both whitaker and paideia but I cannot choose pick one=no selection. I think this would be a super quick workaround to implement. what do u think?

**Comment by irina060981** [comment]
No, it is not a good solution - because all drop-downs should work similiar way, every exception leads to bigger problems in future.

I decided to do the following way (for better consistency).
An application checks if there are defined no dictionaries for short definitions or chosen not Whitaker - then whitaker definitions would be cleared.

This way all dictionary options work similiar way.

**Comment by irina060981** [comment]
Will upload to release later

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
this is fixed in  Alpheios Reading Tools 3.4.1 build incr-3.4.x.20211201209
Alpheios Components 3.3.3-incr-3.4.x.20211125318 build i331-la-lat-update-lang.20211201494 
tested in FF/Mac and PC
