### ISSUE TITLE
Dictionaries only working for some words

### ISSUE THREAD

**Issue by FynnWaelsing** [alpheios-project/webextension#350]
Extension version: 3.3.4
Browser: Chrome Version 99.0.4844.51

The Chrome browser extension seems to not be able to pull up dictionary entries for many Greek words, simply saying "undefined." I've turned on all the available dictionaries in the settings and often get nothing other than the short entry definition. The words that do and do not have definitions does not seem to fit any pattern.

Without definition:
![image](https://user-images.githubusercontent.com/45303748/158070251-94718e4c-538b-4017-a5ad-5501002d3b10.png)
![image](https://user-images.githubusercontent.com/45303748/158070261-82b90bab-e646-4b6c-a1be-a4e0a0135d0f.png)
![image](https://user-images.githubusercontent.com/45303748/158070272-bcc50068-ecc9-4579-bba0-4357487e311b.png)

With definition:
![image](https://user-images.githubusercontent.com/45303748/158070333-403af981-3f39-4bf2-9d3d-f1cc019d4398.png)
![image](https://user-images.githubusercontent.com/45303748/158070342-2d57578a-2e13-4aa6-9f44-74ad67494c54.png)

**Comment by balmas** [comment]
Thank you for letting us know.  The servers were down but it should be resolved now.

**Comment by FynnWaelsing** [comment]
Great to hear, thanks!
