### ISSUE TITLE
Apply Alpheios styles and icons to Extension UI

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#4]
we should from the outset make sure we are using mobile-friendly styles, but we want to retain alpheios colors and icons. The original alpheios css can be found at https://github.com/alpheios-project/ff-basic-reader/tree/master/skin 
I also need to dig out the old style guide for reference, will keep looking for that.

**Comment by kirlat** [comment]
Are you suggesting to use a Bootstrap framework (http://getbootstrap.com/) for the WebExtension UI? It could be too heavy for what we have right now, and a CSS Grid can replace a Bootstrap grid on many occasions. But from another point Bootstrap is a de-facto standard library for UI work; version 4 is highly modular and with with SCSS and build tools can eliminate features that are not required. However, I don't like Bootstrap's jQuery dependency. Or was it something else you were referring to?

Thanks for pointing me to the styles. Do we have icons in any vector format? I think an SVG would be the best way to go, but from other formats we can convert to SVG too. Chorme/FF require icons in a bunch of different sizes, including some non-standard 19x19. It would be great to have an SVG source to be able to generate icons from it.

**Comment by balmas** [comment]
I'm not wedded to the idea of Bootstrap, just want us to be able to take advantage of standard css for dealing with multiple media. 

Sadly, I don't have the Alpheios icons in vector format. We can have that done though. 

Let's talk about all of this on Monday!

**Comment by balmas** [comment]
Notes from conversation today:

- we may take bits and pieces that we need from bootstrap but for now want to avoid the overhead. 
- we agree on using scss via sass where needed
- might want to look at some lightweight alternatives to boostrap: some to consider might be 
https://bulma.io or https://purecss.io/ 
- but there is also no need to use a framework if it doesn't provide value. we can postpone a decision about this until we're clearer on what exactly we need
- main concern is to avoid reinventing solutions for responsive design while not adding alot of unnecessary work to override framework defaults

**Comment by balmas** [comment]
we should also begin keeping a list of the things we need from a designer, such as specific icons, etc.

**Comment by balmas** [comment]
see #6 - we agreed to try use of ui-kit as the underlying css framework for this

**Comment by balmas** [comment]
I think we can close this now. Will enter individual items for specific UI requests.
