### ISSUE TITLE
separate verb permutation views from pofs views in inflection select box

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#47]
in the inflection tables

per @abrasax we want the verb permutations to be selectable separate from the views of different parts of speech

**Comment by balmas** [comment]
Related to this, @abrasax requests to change the displayed title for all of the different verb permutations say "Verb Conjugation" and to drop the word "verb" from the names displayed in the select box.

**Comment by kirlat** [comment]
The first part should be implemented with f58e980baaf65b94b8d1b10985f114dff90427be.

**Comment by kirlat** [comment]
Titles should be fixed with b45934e397db17e8563fab4e45f19515d525e1b2.
