### ISSUE TITLE
experiment with different displays of the logo in the popup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#51]
@abrasax feels the header is too prominent. 

Let's experiment with a few different options. Maybe we could move the notifications to the bottom above the status bar and then put the logo in the left on the status bar and the status text on the right?

**Comment by balmas** [comment]
![image 4](https://user-images.githubusercontent.com/644870/35584421-fdeb6e0a-05c2-11e8-9abf-05c46915a52f.png)

Ok, @kirlat let's go with this one. Thank you!!

**Comment by kirlat** [comment]
4f59876e76692a0b8396613cd0c525f09a84b9df implements this.

**Comment by balmas** [comment]
looks fantastic. thank you!
