### ISSUE TITLE
streamline panel display

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#52]
@abrasax would like similar streamlining done to the panel as was done in the popup. Reduction of logo and header/footer.

**Comment by kirlat** [comment]
Updated in f1d62a7105a97f21bc77757895636f45049d4167.

I replaced a logo of icon and text with just an icon and that provided enough space to move a selection text and language up, next to it. With this, I think, there is no reason to move an icon logo to the bottom. Grouping everything at top allows to eliminate a bottom area completely, gaining more space.

Mobile users will most likely not be happy with a more compact design, but probably we can make a separate skin for them.
