### ISSUE TITLE
would like small/medium/large font/icon options

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#57]
Mark says he would prefer a smaller font/icon sizes be the default. This is likely to be a user preference thing. Maybe we could offer the user 2 or 3 options (small/medium/large)? This applies to both the base text font size (e.g. in the popup and panel) and the icon size.

**Comment by kirlat** [comment]
This can be a little tricky as we need to carefully base all font and probably some other element's sizes like spacing and buttons on a base font size (use of "rem" as a base unit might help). And yet we have to avoid any interference with a font sizing set by a host page.

But I think it would be a nice feature to have, and I think this can be done.

I was also thinking if we can add support for basic skins. Not to change the shape of elements themselves, but allow to switch between different pre-set color combinations (dark/light, etc.). With SCSS variables this should be even easier to do than font options, yet it could probably be an important value for users.

**Comment by balmas** [comment]
moved to components.
