### ISSUE TITLE
scrollbars appear unnecessarily in the popup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#58]
sometimes we get a horizontal scroll bar even when there isn't anything to scroll. would be nice to eliminate this.

**Comment by kirlat** [comment]
That's probably due to spaces before and after content that increases content's height so that it does not fit a content container. We could probably try to tweak a content height threshold to fix that in an easy way.

**Comment by balmas** [comment]
but interestingly, the scrollbars don't seem appear at all in Chrome on the Mac, even when they should.

**Comment by balmas** [comment]
the lack of scrollbars in the mac is an OS preferences. The latest Mac OS has changed the way scrollbars behave generally. If you set scrollbars to show always on the mac, they will appear in the popup.

**Comment by balmas** [comment]
moved to components repository.
