### ISSUE TITLE
make credits link in popup smaller and flush to bottom

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#64]
make credits link in popup smaller and flush to bottom

**Comment by kirlat** [comment]
I was thinking about it, and I'm wondering if we have any reason to have it as a popup. Maybe we can have it as a collapsible text block, where we would have a little plus or a caret down sign near the "Credits" word that that will expand it downwards showing the full credit text? Something like a "Toggle" element in UIKit by functionality (https://getuikit.com/docs/toggle), but with a different toggle element design.

I believe a popup within a popup might not be not the very best UI option, especially for mobile users. I think it would probably be better to have no more than one level of popups. What do you think about that?

**Comment by balmas** [comment]
I agree on the popup point. I think probably the approach to both the morphology credits and the definition sources (#59) needs some work post-alpha.  There is currently a little disconnect between the data model and the ui representation that I glossed over with css and which needs some explanation.

The data behind this is all current represented by the ResourceProviderProxy which can wrap an entire lexeme as well as individual definitions in a DefinitionSet.  Currently there are two possible sources of resource providers: the morphological analyzer and the lexicon service. The morphological analyzers may be the provider for both the morphological data AND definitions. Lexicon services can provide definitions and a single DefinitionSet on a lexeme may itself contain multiple providers.  And although right now we only have a single morphological analyzer applied per language, in the future we may offer users the choice to have multiple analyzers applied, in the same way we have multiple lexicons.

But, from average user's perspective, they probably rarely care about which engine supplied the morphology. The may more likely care about which source was used for a definition, particularly if they are using multiple at once.   From a community perspective, we also do need to make sure that we credit the projects that have provided these free resources to us.

So there's alot of complexity behind the populating of the resource providers that we generally want to hide from the user but still make it possible to be as precise as possible about who provided what.

**Comment by balmas** [comment]
But for the alpha, perhaps we can just combine and dedupe the providers and present them all in a single toggle activated block, and worry about being more precise later. @kirlat what do you think?

**Comment by kirlat** [comment]
I agree that combining all credits would be a good idea for now. We can always switch to showing more detailed and precisely placed credits information later. But if we do it now, I think we risk to delay alpha even more, without any particular necessity (as I see it) for that.

**Comment by balmas** [comment]
@kirlat I have an initial implementation of the combined credits and toggle but if you can make it look better I would be very grateful.

**Comment by balmas** [comment]
done.
