### ISSUE TITLE
popup size refinement requests

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#70]
Balancing act with the size of the popup -- ideally we want to expand it to fit the entire contents of the popup and avoiding scrollbars when we can, but we also want to keep it above the fold. Not sure both of these are achievable for all screen resolutions and sizes

**Comment by kirlat** [comment]
I think it is possible. We are already determining viewport dimensions and checking if a popup fits in. This should be pretty similar.

**Comment by balmas** [comment]
closing this as dupe of #73
