### ISSUE TITLE
getting caught in endless loop in popup dimensions calculations

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#72]
If you click on a number of words in fast succession the code gets caught up looping through calculating dimensions of the popup.
I think this was introduced with use of the vue updated hook

**Comment by balmas** [comment]
Not sure if it's caused by a combination of use of vue updated and the changes I've made to populate popupData.data.providers in 46c37ade1a24a9fd6e5308cd2ae27ec0628776e2

**Comment by balmas** [comment]
yep, that appears to be it. changing the dom for the providers is sending it into spasms.

**Comment by balmas** [comment]
@kirlat for the sake of stability of the alpha, I've removed the use of the vue updated event here in favor of a more explicit approach which just updates a counter whenever we update data in the popup, with a watcher on that which sets the contentHeight. Let me know what you think. It's in 8f8d78905f847ba818263567dc41872c4f985b7e

**Comment by kirlat** [comment]
I think your fix should work quite well. I would like to investigate it post-alpha to see what was going on with a `update` callback. We probably don't have enough time to investigate that right now.

**Comment by balmas** [comment]
Yes, I agree. Will add this to the issue list in the components repository. Thanks!
