### ISSUE TITLE
Add user accounts

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#80]
We should be able to use the Identity API for this https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/identity

This would be a prerequisite to social media sharing features, as well as user learning model, etc.

**Comment by kirlat** [comment]
I think it would be a great feature to have.

**Comment by balmas** [comment]
Sample extension
https://github.com/mdn/webextensions-examples/tree/master/google-userinfo

**Comment by balmas** [comment]
Need to consider back-end service and identity provider options. This article is useful
https://theiconic.tech/authentication-an-in-depth-look-at-aws-cognito-658336515169

**Comment by kirlat** [comment]
Thanks for the useful information, I will study that.

I also might be worth noting that Google starts to add fingerprint support to Chrome: https://www.theverge.com/2018/9/14/17859070/google-fingerprint-support-chrome-70-android-mac-beta

**Comment by balmas** [comment]
closing this issue in favor of individual issues for remaining work
