### ISSUE TITLE
add option to suppress panel opening upon activation

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#85]
requested by @abrasax : we should give the user an option to not open the panel by default each time the extension is activated.

**Comment by balmas** [comment]
alternatively (either instead of this or in addition): upon first activation show plan but allow clicking anywhere or moving the mouse  to close it.

**Comment by irina060981** [comment]
1) Solution for closing panel on outside click
in component repo - alpheios-project/components#119

**Comment by irina060981** [comment]
Merged
