### ISSUE TITLE
make "Activate/Deactivate" menu items state-sensitive

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#9]
if Alpheios is loaded and active, only Deactivate show be enabled and vice-versa.

**Comment by kirlat** [comment]
I will work on that.

**Comment by balmas** [comment]
this is working. one thing that's a little confusing is that the context menu options show as a submenu of an "alpheios reading tools" menu item when there are more than one (e.g. deactivate and open panel) and directly in the menu when there is only one.  I think it might be better to always have them in a submenu. What do you think @kirlat ?
