### ISSUE TITLE
don't update ui controller state

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#93]
With https://github.com/alpheios-project/components/commit/08ec8733d1d0f6fcc9362fb55783fefeb3895fe4 for https://github.com/alpheios-project/components/issues/109 and https://github.com/alpheios-project/components/issues/102, we no longer should call uiControlller.updateLanguage from the text selection event handler in the webextension code

**Comment by irina060981** [comment]
Removed 
https://github.com/alpheios-project/webextension/pull/96

**Comment by irina060981** [comment]
Merged and closed
