### ISSUE TITLE
Different windows in Firefox has the same ID

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/webextension#98]
While solving the issue 
https://github.com/alpheios-project/webextension/issues/89

I have found out that diffrent tabs inside one window have it own activation.

But if we open two windows for firefox - then they will have the same activation status and activate/deactivate will reflect for both synchronously.

![image](https://user-images.githubusercontent.com/12377640/41657955-51765718-74d8-11e8-8b99-2a34173e63e0.png)

**Comment by balmas** [comment]
@irina060981 can you look into whether there is a window id available from the webextension api that we could use in combination with the tab id to make sure we have unique state per window and tab?

**Comment by irina060981** [comment]
Ok, Bridget, here are my results:

1) when we use **browser.tabs.onActivated** in **BackgroundProcess.initialize** - it has argument **info** passed to **BackgroundProcess.tabActivationListener**
    this argument is an object with two values - tabId (that we currently use) and windowId
   for example from my debug 
   
![image](https://user-images.githubusercontent.com/12377640/42990587-682c4a14-8c46-11e8-8a37-3e470dc30c28.png)

  **tabActivationListener1** - **info** argument
  **tabActivationListener2** - history array for tracking its changing

you could see that 
1 case - new tab appears with new tabID and the same windowId
2 case - i have moved tab to a new window - it has the same tabId and a new windowId

2) These values could be changed through such events:
     tabs.onActivated
     tabs.onAttached
     tabs.onDetached
    here are the full list of tab's events - https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs

**Comment by balmas** [comment]
ok, so I think we need to use windowId in combination with the tabId wherever we currently use tabId.  Maybe we could have a method createTabId which takes the details object from the event and constructs our internal tabId as a combination of the window and tab id?  

Another, more complicated option would be to have a parent windows property on the BackgroundProcess object, and then to manage the tabs within each window, but I'm not sure a change of that scope is really necessary.  

@kirlat do you have any opinion on this?

**Comment by kirlat** [comment]
This is interesting:

> 2 case - i have moved tab to a new window - it has the same tabId and a new windowId
What does it do if a new window already has the same tab ID? Does it change a tab ID so it be unique? (but this might be hard to test)

Is it possible for you to test it in Chrome? How does it behave there? If we change that, I'd better come up with solution that will work cross-browser.

I think maybe we can make tab an object with two props (tabID and windowID, and maybe browser ID and version if those tab and window IDs are browser dependent) and provide a compare method that will tell if two tab objects are the same? This might have two advantages:
1. A compare method will allow to provide custom compare logic (browser dependent, for example, or when we know some rules of how tab IDs changes when it's moved from one window to the other)
2. It will allow to accommodate future browser changes (what if some browser decides to use some other type of ID or what if format be changed in a next browser version?) without affecting the outside code. Everything will be within the tab, so we can add any new IDs to it and change comparison logic, but the outside code will not know about it and will continue to work as before.

What do you think?

**Comment by irina060981** [comment]
I have tried these scenario in both browsers (chrome and firefox)

**1) add one tab**
Chrome
![chrome - 1 new tab1](https://user-images.githubusercontent.com/12377640/43033105-5c5b543e-8d07-11e8-96ce-61570763c851.PNG)
Firefox
![firefox - 1 new tab1](https://user-images.githubusercontent.com/12377640/43033107-60757a54-8d07-11e8-8e53-7e9b0d707aca.PNG)

**2) add another tab**
Chrome
![chrome - 2 new tab](https://user-images.githubusercontent.com/12377640/43033115-77f9baf0-8d07-11e8-9cf6-0262fa0e44fc.PNG)
Firefox
![firefox - 2 new tab](https://user-images.githubusercontent.com/12377640/43033117-7f2c79d4-8d07-11e8-9847-94cdbef2fc17.PNG)

**3) deattach tab to a new window**
Chrome
![chrome - 3 deattachtab](https://user-images.githubusercontent.com/12377640/43033124-95cc64ec-8d07-11e8-86f6-69593f0be3ce.PNG)
Firefox
![firefox - 3 deattachtab](https://user-images.githubusercontent.com/12377640/43033126-9a65c872-8d07-11e8-9f57-d7b498f00739.PNG)

**4) deattach tab to a previous  window**
Chrome
![chrome - 4 attachtab](https://user-images.githubusercontent.com/12377640/43033128-a71ed982-8d07-11e8-8f1f-4585743d2568.PNG)
Firefox
![firefox - 4 attachtab](https://user-images.githubusercontent.com/12377640/43033132-b12f7756-8d07-11e8-888d-b2cf91e7d9c4.PNG)

**Comment by irina060981** [comment]
**Second Scenario**

**1) add one tab**
Chrome
![image](https://user-images.githubusercontent.com/12377640/43033149-5c7ab7e2-8d08-11e8-9eab-63ca1c8a5578.png)
Firefox
![image](https://user-images.githubusercontent.com/12377640/43033151-6a2281cc-8d08-11e8-9551-91a9a038ac98.png)

**2) open another tab**
Chrome
![image](https://user-images.githubusercontent.com/12377640/43033165-92807c82-8d08-11e8-86b2-2d7d9081ecfd.png)
Firefox
![image](https://user-images.githubusercontent.com/12377640/43033166-9ed09666-8d08-11e8-956a-3585d2350952.png)

**3) deattach tab to a new window**
Chrome
![image](https://user-images.githubusercontent.com/12377640/43033168-b21217f4-8d08-11e8-86fc-40d090ecddc0.png)
Firefox
![image](https://user-images.githubusercontent.com/12377640/43033173-d3609728-8d08-11e8-9db9-39edcb456c6e.png)

**4) open a new tab in a new window**
Chrome
![image](https://user-images.githubusercontent.com/12377640/43033178-f4a81910-8d08-11e8-94e9-6dcb9a58b111.png)
Firefox
![image](https://user-images.githubusercontent.com/12377640/43033179-005e1688-8d09-11e8-9cef-5e1c7a4fb2b7.png)

**5) open a new tab in an old window**
Chrome
![image](https://user-images.githubusercontent.com/12377640/43033188-1911709e-8d09-11e8-8ff4-26b7294ecf47.png)
Firefox
![image](https://user-images.githubusercontent.com/12377640/43033191-23ff0ebc-8d09-11e8-8113-3b6bce6a6d52.png)

**Comment by irina060981** [comment]
And I could see some points:

1) every new tab has a new ID - and it doesn't change when we move it to a window
2) every tab has a windowID - and it changes from attaching to a window
3) the behaviour is the same in firefox and chrome

**Comment by balmas** [comment]
I like the suggestion of creating a tab object with properties for tabId and windowId and a compare method.

**Comment by balmas** [comment]
Per discussion today, Irina will make this change.

**Comment by irina060981** [comment]
Created changes - https://github.com/alpheios-project/webextension/pull/102

**Comment by irina060981** [comment]
Merged and closed
